// ui/src/vue/App.vue
<!-- Vue port of src/App.tsx. Owns global state: conversation list,
     current/viewed conversation, drawer, command palette + modals, ephemeral
     terminals, the global SSE stream, URL/slug sync, page title, and global
     keyboard shortcuts. Renders ConversationDrawer, ChatInterface,
     CommandPalette and the modals.

     Worker pool: the React App wrapped everything in @pierre/diffs
     WorkerPoolContextProvider. PatchTool.vue uses the @pierre/diffs SSR
     (synchronous) API and needs no worker pool, so no provider is rendered
     here. -->
<template>
  <!-- Loading gate -->
  <div v-if="loading && conversations.length === 0" class="loading-container">
    <div class="loading-content">
      <div class="spinner" style="margin: 0 auto 1rem" />
      <p class="text-secondary">{{ t("loading") }}</p>
    </div>
  </div>

  <div v-else-if="error && conversations.length === 0" class="error-container">
    <div class="error-content">
      <p class="error-message" style="margin-bottom: 1rem">{{ error }}</p>
      <button class="btn-primary" @click="loadConversations">{{ t("retry") }}</button>
    </div>
  </div>

  <template v-else>
    <div v-if="banner" class="top-banner" :title="banner">{{ banner }}</div>
    <div class="app-container">
      <ConversationDrawer
        :is-open="drawerOpen"
        :is-collapsed="drawerCollapsed"
        :conversations="conversations"
        :current-conversation-id="currentConversationId"
        :viewed-conversation="viewedConversation"
        :show-active-trigger="showActiveTrigger"
        @close="drawerOpen = false"
        @toggle-collapse="toggleDrawerCollapsed"
        @select-conversation="selectConversation"
        @new-conversation="startNewConversation"
        @archived="handleConversationArchived"
        @unarchived="handleConversationUnarchived"
        @renamed="handleConversationRenamed"
      />

      <div class="main-content">
        <ChatInterface
          :conversation-id="currentConversationId"
          :stream-status="streamStatus"
          :reconnect-nonce="reconnectNonce"
          :on-open-drawer="() => (drawerOpen = true)"
          :on-new-conversation="startNewConversation"
          :on-select-conversation="selectConversation"
          :on-archive-conversation="archiveFromChat"
          :current-conversation="currentConversation"
          :on-conversation-update="updateConversation"
          :on-first-message="handleFirstMessage"
          :on-draft-created="onDraftCreated"
          :on-distill-new-generation="handleDistillNewGeneration"
          :most-recent-cwd="mostRecentCwd"
          :is-drawer-collapsed="drawerCollapsed"
          :on-toggle-drawer-collapse="toggleDrawerCollapsed"
          :open-diff-viewer-trigger="diffViewerTrigger"
          :open-git-graph-trigger="gitGraphTrigger"
          :open-terminal-trigger="terminalTrigger"
          :models-refresh-trigger="modelsRefreshTrigger"
          :cwd-sync-trigger="cwdSyncTrigger"
          :on-open-models-modal="() => (modelsModalOpen = true)"
          :ephemeral-terminals="ephemeralTerminals"
          :set-ephemeral-terminals="setEphemeralTerminals"
          :on-terminal-attached="handleTerminalAttached"
          :on-terminal-close="handleTerminalClose"
          :navigate-user-message-trigger="navigateUserMessageTrigger"
          :on-conversation-unarchived="handleConversationUnarchived"
        />
      </div>

      <CommandPalette
        :is-open="commandPaletteOpen"
        :conversations="topLevelConversations"
        :current-conversation="currentConversation || null"
        :has-cwd="commandPaletteHasCwd"
        @close="onCommandPaletteClose"
        @new-conversation="
          () => {
            startNewConversation();
            commandPaletteOpen = false;
          }
        "
        @new-conversation-with-cwd="
          (cwd) => {
            startNewConversationWithCwd(cwd);
            commandPaletteOpen = false;
          }
        "
        @set-conversation-cwd="
          (cwd) => {
            setConversationCwd(cwd);
            commandPaletteOpen = false;
          }
        "
        @select-conversation="
          (c) => {
            selectConversation(c);
            commandPaletteOpen = false;
          }
        "
        @archive-conversation="archiveFromPalette"
        @open-diff-viewer="
          () => {
            diffViewerTrigger++;
            commandPaletteOpen = false;
          }
        "
        @open-git-graph="
          () => {
            gitGraphTrigger++;
            commandPaletteOpen = false;
          }
        "
        @open-terminal="
          () => {
            terminalTrigger++;
            commandPaletteOpen = false;
          }
        "
        @open-models-modal="
          () => {
            modelsModalOpen = true;
            commandPaletteOpen = false;
          }
        "
        @open-notifications-modal="
          () => {
            notificationsModalOpen = true;
            commandPaletteOpen = false;
          }
        "
        @open-feature-flags-modal="
          () => {
            featureFlagsModalOpen = true;
            commandPaletteOpen = false;
          }
        "
        @next-conversation="navigateToNextConversation"
        @previous-conversation="navigateToPreviousConversation"
        @next-user-message="navigateToNextUserMessage"
        @previous-user-message="navigateToPreviousUserMessage"
      />

      <ModelsModal
        :is-open="modelsModalOpen"
        @close="
          () => {
            modelsModalOpen = false;
            focusMessageInputIfUnfocused();
          }
        "
        @models-changed="modelsRefreshTrigger++"
      />

      <NotificationsModal
        :is-open="notificationsModalOpen"
        @close="
          () => {
            notificationsModalOpen = false;
            focusMessageInputIfUnfocused();
          }
        "
      />

      <FeatureFlagsModal
        :is-open="featureFlagsModalOpen"
        @close="
          () => {
            featureFlagsModalOpen = false;
            focusMessageInputIfUnfocused();
          }
        "
      />

      <div v-if="drawerOpen" class="backdrop hide-on-desktop" @click="drawerOpen = false" />
    </div>
  </template>
</template>

<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref, watch } from "vue";
import ChatInterface from "./components/ChatInterface.vue";
import ConversationDrawer from "./components/ConversationDrawer.vue";
import CommandPalette from "./components/CommandPalette.vue";
import ModelsModal from "./components/ModelsModal.vue";
import NotificationsModal from "./components/NotificationsModal.vue";
import FeatureFlagsModal from "./components/FeatureFlagsModal.vue";
import type { EphemeralTerminal } from "./components/terminalTypes";
import { focusMessageInputIfUnfocused } from "../utils/focusMessageInput";
import {
  type Conversation,
  type ConversationWithState,
  type ConversationListPatchEvent,
} from "../types";
import { api } from "../services/api";
import { messageStore } from "../services/messageStore";
import { applyConversationListPatch } from "../services/conversationListStream";
import { connectGlobalStream, type StreamStatus } from "../services/globalStream";
import { handleNotificationEvent } from "../services/notifications";
import { useI18n } from "./composables/i18n";

const { t } = useI18n();

// ---- URL/slug helpers ----
function isGeneratedId(slug: string | null): boolean {
  if (!slug) return true;
  return /^c[a-z0-9]+$/i.test(slug);
}
function getSlugFromPath(): string | null {
  const path = window.location.pathname;
  if (path.startsWith("/c/")) {
    const slug = path.slice(3);
    if (slug) return slug;
  }
  return null;
}
function isNewPath(): boolean {
  return window.location.pathname === "/new";
}

// Captured BEFORE render so URL-updating effects don't clobber it.
const initialSlugFromUrl = getSlugFromPath();
const initialIsNew = isNewPath();

function updateUrlWithSlug(conversation: Conversation | undefined) {
  const currentSlug = getSlugFromPath();
  let newSlug: string | null = null;
  if (conversation?.slug && !isGeneratedId(conversation.slug)) {
    newSlug = conversation.slug;
  } else if (conversation?.is_draft) {
    newSlug = conversation.conversation_id;
  }
  if (currentSlug !== newSlug) {
    if (newSlug) window.history.replaceState({}, "", `/c/${newSlug}`);
    else window.history.replaceState({}, "", "/");
  }
}

function updatePageTitle(conversation: Conversation | undefined) {
  const hostname = window.__SHELLEY_INIT__?.hostname;
  const parts: string[] = [];
  if (conversation?.slug && !isGeneratedId(conversation.slug)) parts.push(conversation.slug);
  if (hostname) parts.push(hostname);
  parts.push("Shelley Agent");
  document.title = parts.join(" - ");
}

const banner = window.__SHELLEY_INIT__?.banner;

// ---- state ----
const conversations = ref<ConversationWithState[]>([]);
const currentConversationId = ref<string | null>(null);
const viewedConversation = ref<Conversation | null>(null);
const drawerOpen = ref(false);
const drawerCollapsed = ref(false);
const commandPaletteOpen = ref(false);
const diffViewerTrigger = ref(0);
const gitGraphTrigger = ref(0);
const terminalTrigger = ref(0);
const modelsModalOpen = ref(false);
const notificationsModalOpen = ref(false);
const featureFlagsModalOpen = ref(false);
const modelsRefreshTrigger = ref(0);
const cwdSyncTrigger = ref(0);
const navigateUserMessageTrigger = ref(0);
const loading = ref(true);
const error = ref<string | null>(null);
const ephemeralTerminals = ref<EphemeralTerminal[]>([]);
const streamStatus = ref<StreamStatus>("connected");
const reconnectNonce = ref(0);
const showActiveTrigger = ref(0);

// ---- non-reactive refs ----
let initialSlugResolved = false;
let conversationListHash: string | null = null;
let globalStreamHandle: { forceReconnect: () => void; close: () => void } | null = null;

// setEphemeralTerminals supports both array and updater-function forms (parity
// with React's setState) so ChatInterface can call it like the React prop.
function setEphemeralTerminals(
  next: EphemeralTerminal[] | ((prev: EphemeralTerminal[]) => EphemeralTerminal[]),
) {
  ephemeralTerminals.value = typeof next === "function" ? next(ephemeralTerminals.value) : next;
}

function handleTerminalAttached(id: string, termId: string) {
  setEphemeralTerminals((prev) => prev.map((tm) => (tm.id === id ? { ...tm, termId } : tm)));
}

function handleTerminalClose(id: string) {
  setEphemeralTerminals((prev) => {
    const tm = prev.find((x) => x.id === id);
    if (tm && tm.termId) {
      fetch(`/api/terminals/${encodeURIComponent(tm.termId)}`, { method: "DELETE" }).catch((err) =>
        console.warn("failed to delete terminal:", err),
      );
    }
    return prev.filter((x) => x.id !== id);
  });
}

// ---- derived ----
const topLevelConversations = computed(() =>
  conversations.value.filter((c) => !c.parent_conversation_id),
);

const currentConversation = computed<ConversationWithState | undefined>(() => {
  const found = conversations.value.find(
    (conv) => conv.conversation_id === currentConversationId.value,
  );
  if (found) return found;
  if (viewedConversation.value?.conversation_id === currentConversationId.value) {
    return {
      ...viewedConversation.value,
      working: false,
      subagent_count: 0,
      max_sequence_id: 0,
    } as ConversationWithState;
  }
  return undefined;
});

const mostRecentCwd = computed(
  () =>
    currentConversation.value?.cwd ||
    (topLevelConversations.value.length > 0 ? topLevelConversations.value[0].cwd : null),
);

const commandPaletteHasCwd = computed(
  () =>
    !!(
      currentConversation.value?.cwd ||
      mostRecentCwd.value ||
      localStorage.getItem("shelley_selected_cwd") ||
      window.__SHELLEY_INIT__?.default_cwd
    ),
);

// ---- navigation ----
function navigateToNextConversation() {
  const list = topLevelConversations.value;
  if (list.length === 0) return;
  const currentIndex = list.findIndex((c) => c.conversation_id === currentConversationId.value);
  const nextIndex = currentIndex < 0 ? 0 : Math.min(currentIndex + 1, list.length - 1);
  const next = list[nextIndex];
  currentConversationId.value = next.conversation_id;
  viewedConversation.value = next;
}
function navigateToPreviousConversation() {
  const list = topLevelConversations.value;
  if (list.length === 0) return;
  const currentIndex = list.findIndex((c) => c.conversation_id === currentConversationId.value);
  const prevIndex = currentIndex < 0 ? 0 : Math.max(currentIndex - 1, 0);
  const prev = list[prevIndex];
  currentConversationId.value = prev.conversation_id;
  viewedConversation.value = prev;
}
function navigateToNextUserMessage() {
  navigateUserMessageTrigger.value = Math.abs(navigateUserMessageTrigger.value) + 1;
}
function navigateToPreviousUserMessage() {
  navigateUserMessageTrigger.value = -(Math.abs(navigateUserMessageTrigger.value) + 1);
}

// ---- conversation list patch handling ----
function recoverConversationListStream() {
  conversationListHash = null;
  globalStreamHandle?.forceReconnect();
}

function handleConversationListPatch(event: ConversationListPatchEvent) {
  const currentHash = conversationListHash;
  if (!event.reset && event.old_hash !== currentHash) {
    console.warn("conversation list patch hash mismatch; recovering via reconnect", {
      eventOldHash: event.old_hash,
      currentHash,
    });
    recoverConversationListStream();
    return;
  }
  const prev = conversations.value;
  let next: ConversationWithState[];
  try {
    next = applyConversationListPatch(prev, event.patch);
  } catch (err) {
    console.error("failed to apply conversation list patch; recovering via reconnect", err, {
      patch: event.patch,
      prevLen: prev.length,
    });
    recoverConversationListStream();
    return;
  }
  const nextIds = new Set(next.map((conv) => conv.conversation_id));
  for (const conv of prev) {
    if (!nextIds.has(conv.conversation_id)) {
      void messageStore.delete(conv.conversation_id);
    }
  }
  for (const conv of next) {
    messageStore.setMaxSequenceIdKnown(conv.conversation_id, conv.max_sequence_id);
    messageStore.setAgentWorking(conv.conversation_id, conv.agent_working);
  }
  conversations.value = next;
  conversationListHash = event.new_hash;
}

// ---- initial slug resolution ----
async function resolveInitialSlug(convs: Conversation[]): Promise<Conversation | null> {
  if (initialSlugResolved) return null;
  initialSlugResolved = true;
  const urlSlug = initialSlugFromUrl;
  if (!urlSlug) return null;
  const existingConv = convs.find((c) => c.slug === urlSlug || c.conversation_id === urlSlug);
  if (existingConv) return existingConv;
  try {
    const conv = await api.getConversationBySlug(urlSlug);
    if (conv) return conv;
  } catch (err) {
    console.error("Failed to resolve slug:", err);
  }
  window.history.replaceState({}, "", "/");
  return null;
}

async function loadConversations() {
  try {
    loading.value = true;
    error.value = null;
    const snapshot = await api.getConversationsSnapshot();
    for (const conv of snapshot.conversations) {
      messageStore.setMaxSequenceIdKnown(conv.conversation_id, conv.max_sequence_id);
    }
    const activeIds = snapshot.conversations.map((c) => c.conversation_id);
    void messageStore.pruneStale(activeIds, 7 * 24 * 60 * 60 * 1000);
    const streamHash = conversationListHash;
    if (!streamHash) {
      conversations.value = snapshot.conversations;
      conversationListHash = snapshot.hash;
    }
    const currentList = streamHash ? conversations.value : snapshot.conversations;
    const topLevel = currentList.filter((c) => !c.parent_conversation_id);

    const slugConv = await resolveInitialSlug(currentList);
    if (slugConv) {
      currentConversationId.value = slugConv.conversation_id;
      viewedConversation.value = slugConv;
    } else if (!initialIsNew && topLevel.length > 0) {
      currentConversationId.value = topLevel[0].conversation_id;
      viewedConversation.value = topLevel[0];
    }
  } catch (err) {
    console.error("Failed to load conversations:", err);
    error.value = "Failed to load conversations. Please refresh the page.";
  } finally {
    loading.value = false;
  }
}

// ---- conversation actions ----
function startNewConversation() {
  if (currentConversation.value?.cwd) {
    localStorage.setItem("shelley_selected_cwd", currentConversation.value.cwd);
  }
  currentConversationId.value = null;
  viewedConversation.value = null;
  window.history.replaceState({}, "", "/new");
  drawerOpen.value = false;
}

function startNewConversationWithCwd(cwd: string) {
  localStorage.setItem("shelley_selected_cwd", cwd);
  currentConversationId.value = null;
  viewedConversation.value = null;
  window.history.replaceState({}, "", "/new");
  drawerOpen.value = false;
  cwdSyncTrigger.value++;
}

function setConversationCwd(cwd: string) {
  localStorage.setItem("shelley_selected_cwd", cwd);
  const conv =
    conversations.value.find((c) => c.conversation_id === currentConversationId.value) ||
    (viewedConversation.value?.conversation_id === currentConversationId.value
      ? viewedConversation.value
      : null);
  if (conv?.is_draft) {
    api.updateDraftCwd(conv.conversation_id, cwd).catch((err) => {
      console.debug("Could not persist draft cwd (likely already promoted):", err);
    });
  }
  cwdSyncTrigger.value++;
}

function selectConversation(conversation: Conversation) {
  currentConversationId.value = conversation.conversation_id;
  viewedConversation.value = conversation;
  drawerOpen.value = false;
}

function toggleDrawerCollapsed() {
  drawerCollapsed.value = !drawerCollapsed.value;
}

function updateConversation(updatedConversation: Conversation) {
  if (updatedConversation.conversation_id === currentConversationId.value) {
    viewedConversation.value = updatedConversation;
  }
}

function handleConversationArchived(
  conversationId: string,
  nextConversation?: Conversation | null,
) {
  void messageStore.delete(conversationId);
  if (currentConversationId.value === conversationId) {
    if (nextConversation && nextConversation.conversation_id !== conversationId) {
      currentConversationId.value = nextConversation.conversation_id;
      viewedConversation.value = nextConversation;
      return;
    }
    const remaining = conversations.value.filter(
      (conv) => conv.conversation_id !== conversationId && !conv.parent_conversation_id,
    );
    currentConversationId.value = remaining.length > 0 ? remaining[0].conversation_id : null;
    viewedConversation.value = remaining.length > 0 ? remaining[0] : null;
  }
}

function handleConversationUnarchived(conversation: Conversation) {
  if (conversation.conversation_id === currentConversationId.value) {
    viewedConversation.value = conversation;
  }
  showActiveTrigger.value++;
}

function handleConversationRenamed(conversation: Conversation) {
  if (conversation.conversation_id === currentConversationId.value) {
    viewedConversation.value = conversation;
  }
}

async function archiveFromChat(conversationId: string) {
  await api.archiveConversation(conversationId);
  handleConversationArchived(conversationId);
}

async function archiveFromPalette(conversationId: string) {
  try {
    await api.archiveConversation(conversationId);
    handleConversationArchived(conversationId);
  } catch (err) {
    console.error("Failed to archive conversation:", err);
  }
}

function onDraftCreated(id: string) {
  currentConversationId.value = id;
}

function onCommandPaletteClose() {
  commandPaletteOpen.value = false;
  focusMessageInputIfUnfocused();
}

async function handleFirstMessage(
  message: string,
  model: string,
  cwd?: string,
  conversationType?: "normal" | "orchestrator",
  subagentBackend?: "shelley" | "claude-cli" | "codex-cli",
  toolOverrides?: Record<string, "on" | "off">,
  thinkingLevel?: "off" | "minimal" | "low" | "medium" | "high" | "xhigh",
) {
  try {
    const hasOverrides = toolOverrides && Object.keys(toolOverrides).length > 0;
    const hasThinking = !!thinkingLevel;
    const convOpts =
      conversationType === "orchestrator" || hasOverrides || hasThinking
        ? {
            ...(conversationType === "orchestrator"
              ? { type: "orchestrator" as const, subagent_backend: subagentBackend || "shelley" }
              : {}),
            ...(hasOverrides ? { tool_overrides: toolOverrides } : {}),
            ...(hasThinking ? { thinking_level: thinkingLevel } : {}),
          }
        : undefined;
    const response = await api.sendMessageWithNewConversation({
      message,
      model,
      cwd,
      conversation_options: convOpts,
    });
    const newConversationId = response.conversation_id;
    messageStore.setAgentWorking(newConversationId, true);
    currentConversationId.value = newConversationId;
  } catch (err) {
    console.error("Failed to send first message:", err);
    error.value = err instanceof Error ? err.message : "Failed to send message";
    throw err;
  }
}

async function handleDistillNewGeneration(
  sourceConversationId: string,
  model: string,
  cwd?: string,
  method?: "default" | "compact",
  instructions?: string,
) {
  try {
    await api.distillNewGeneration(sourceConversationId, model, cwd, method, instructions);
    currentConversationId.value = sourceConversationId;
  } catch (err) {
    console.error("Failed to distill into new generation:", err);
    error.value = "Failed to distill into new generation";
    throw err;
  }
}

// ---- global keyboard shortcuts (incl. Ctrl+M chord) ----
let chordPending = false;
let chordTimer: number | null = null;
function clearChord() {
  chordPending = false;
  if (chordTimer !== null) {
    clearTimeout(chordTimer);
    chordTimer = null;
  }
}
const isMac = navigator.platform.toUpperCase().includes("MAC");

function handleKeyDown(e: KeyboardEvent) {
  if (chordPending) {
    clearChord();
    if (e.key === "n" || e.key === "N") {
      e.preventDefault();
      navigateToNextUserMessage();
      return;
    }
    if (e.key === "p" || e.key === "P") {
      e.preventDefault();
      navigateToPreviousUserMessage();
      return;
    }
    return;
  }

  if (e.ctrlKey && !e.metaKey && !e.altKey && (e.key === "m" || e.key === "M")) {
    e.preventDefault();
    chordPending = true;
    chordTimer = window.setTimeout(clearChord, 1500);
    return;
  }

  if (isMac && e.ctrlKey && !e.metaKey) return;
  const modifierPressed = isMac ? e.metaKey : e.ctrlKey;

  if (modifierPressed && e.key === "k") {
    e.preventDefault();
    commandPaletteOpen.value = !commandPaletteOpen.value;
    return;
  }

  if (e.altKey && !e.ctrlKey && !e.metaKey && !e.shiftKey && e.key === "ArrowDown") {
    e.preventDefault();
    navigateToNextConversation();
    return;
  }

  if (e.altKey && !e.ctrlKey && !e.metaKey && !e.shiftKey && e.key === "ArrowUp") {
    e.preventDefault();
    navigateToPreviousConversation();
    return;
  }
}

// ---- popstate (back/forward + SubagentTool navigation) ----
async function handlePopState() {
  if (isNewPath()) {
    currentConversationId.value = null;
    viewedConversation.value = null;
    return;
  }
  const slug = getSlugFromPath();
  if (!slug) return;
  const existingConv = conversations.value.find(
    (c) => c.slug === slug || c.conversation_id === slug,
  );
  if (existingConv) {
    currentConversationId.value = existingConv.conversation_id;
    viewedConversation.value = existingConv;
    return;
  }
  try {
    const conv = await api.getConversationBySlug(slug);
    if (conv) {
      currentConversationId.value = conv.conversation_id;
      viewedConversation.value = conv;
    }
  } catch (err) {
    console.error("Failed to navigate to conversation:", err);
  }
}

// ---- page title + URL sync ----
watch(
  [currentConversationId, viewedConversation, conversations],
  () => {
    const currentConv =
      viewedConversation.value?.conversation_id === currentConversationId.value
        ? viewedConversation.value
        : conversations.value.find((conv) => conv.conversation_id === currentConversationId.value);
    if (currentConv) {
      updatePageTitle(currentConv);
      updateUrlWithSlug(currentConv);
    }
  },
  { deep: false },
);

// ---- lifecycle ----
onMounted(() => {
  // Hydrate persistent terminals from the server.
  let cancelled = false;
  fetch("/api/terminals")
    .then((r) => (r.ok ? r.json() : []))
    .then((rows: Array<{ id: string; command: string; cwd: string; created_at: string }>) => {
      if (cancelled || !Array.isArray(rows) || rows.length === 0) return;
      setEphemeralTerminals((prev) => {
        const have = new Set(prev.map((tm) => tm.termId).filter(Boolean));
        const restored: EphemeralTerminal[] = rows
          .filter((r) => !have.has(r.id))
          .map((r) => ({
            id: r.id,
            termId: r.id,
            command: r.command,
            cwd: r.cwd,
            createdAt: new Date(r.created_at || Date.now()),
          }));
        return [...restored, ...prev];
      });
    })
    .catch((err) => console.warn("failed to fetch persistent terminals:", err));
  terminalsHydrationCancel = () => {
    cancelled = true;
  };

  loadConversations();

  globalStreamHandle = connectGlobalStream({
    getHash: () => conversationListHash,
    onListPatch: handleConversationListPatch,
    onNotificationEvent: handleNotificationEvent,
    onStatusChange: (status) => (streamStatus.value = status),
    onReconnect: () => {
      reconnectNonce.value++;
    },
  });

  document.addEventListener("keydown", handleKeyDown);
  window.addEventListener("popstate", handlePopState);
});

let terminalsHydrationCancel: (() => void) | null = null;

onUnmounted(() => {
  terminalsHydrationCancel?.();
  globalStreamHandle?.close();
  globalStreamHandle = null;
  document.removeEventListener("keydown", handleKeyDown);
  window.removeEventListener("popstate", handlePopState);
  clearChord();
});
</script>

// ui/src/App.tsx
import React, { useState, useEffect, useCallback, useMemo, useRef } from "react";
import { WorkerPoolContextProvider } from "@pierre/diffs/react";
import type { SupportedLanguages } from "@pierre/diffs";
import ChatInterface from "./components/ChatInterface";
import type { EphemeralTerminal } from "./components/TerminalPanel";
import ConversationDrawer from "./components/ConversationDrawer";
import CommandPalette from "./components/CommandPalette";
import ModelsModal from "./components/ModelsModal";
import NotificationsModal from "./components/NotificationsModal";
import { Conversation, ConversationWithState, ConversationListPatchEvent } from "./types";
import { api } from "./services/api";
import { conversationCache } from "./services/conversationCache";
import {
  applyConversationListPatch,
  connectConversationListStream,
} from "./services/conversationListStream";
import { useI18n } from "./i18n";

// Worker pool configuration for @pierre/diffs syntax highlighting
// Workers run tokenization off the main thread for better performance with large diffs
const diffsPoolOptions = {
  workerFactory: () => new Worker("/diffs-worker.js"),
};

// Languages to preload in the highlighter (matches PatchTool.tsx langMap)
const diffsHighlighterOptions = {
  langs: [
    "typescript",
    "tsx",
    "javascript",
    "jsx",
    "python",
    "ruby",
    "go",
    "rust",
    "java",
    "c",
    "cpp",
    "csharp",
    "php",
    "swift",
    "kotlin",
    "scala",
    "bash",
    "sql",
    "html",
    "css",
    "scss",
    "json",
    "xml",
    "yaml",
    "toml",
    "markdown",
  ] as SupportedLanguages[],
};

// Check if a slug is a generated ID (format: cXXXX where X is alphanumeric)
function isGeneratedId(slug: string | null): boolean {
  if (!slug) return true;
  return /^c[a-z0-9]+$/i.test(slug);
}

// Get slug from the current URL path (expects /c/<slug> format)
function getSlugFromPath(): string | null {
  const path = window.location.pathname;
  // Check for /c/<slug> format
  if (path.startsWith("/c/")) {
    const slug = path.slice(3); // Remove "/c/" prefix
    if (slug) {
      return slug;
    }
  }
  return null;
}

function isNewPath(): boolean {
  return window.location.pathname === "/new";
}

// Capture the initial slug from URL BEFORE React renders, so it won't be affected
// by the useEffect that updates the URL based on current conversation.
const initialSlugFromUrl = getSlugFromPath();
const initialIsNew = isNewPath();

// Update the URL to reflect the current conversation slug
function updateUrlWithSlug(conversation: Conversation | undefined) {
  const currentSlug = getSlugFromPath();
  const newSlug =
    conversation?.slug && !isGeneratedId(conversation.slug) ? conversation.slug : null;

  if (currentSlug !== newSlug) {
    if (newSlug) {
      window.history.replaceState({}, "", `/c/${newSlug}`);
    } else {
      window.history.replaceState({}, "", "/");
    }
  }
}

function updatePageTitle(conversation: Conversation | undefined) {
  const hostname = window.__SHELLEY_INIT__?.hostname;
  const parts: string[] = [];

  if (conversation?.slug && !isGeneratedId(conversation.slug)) {
    parts.push(conversation.slug);
  }
  if (hostname) {
    parts.push(hostname);
  }
  parts.push("Shelley Agent");

  document.title = parts.join(" - ");
}

function App() {
  const { t } = useI18n();
  const [conversations, setConversations] = useState<ConversationWithState[]>([]);
  const [currentConversationId, setCurrentConversationId] = useState<string | null>(null);
  // Track viewed conversation separately (needed for subagents which aren't in main list)
  const [viewedConversation, setViewedConversation] = useState<Conversation | null>(null);
  const [drawerOpen, setDrawerOpen] = useState(false);
  const [drawerCollapsed, setDrawerCollapsed] = useState(false);
  const [commandPaletteOpen, setCommandPaletteOpen] = useState(false);
  const [diffViewerTrigger, setDiffViewerTrigger] = useState(0);
  const [gitGraphTrigger, setGitGraphTrigger] = useState(0);
  const [modelsModalOpen, setModelsModalOpen] = useState(false);
  const [notificationsModalOpen, setNotificationsModalOpen] = useState(false);
  const [modelsRefreshTrigger, setModelsRefreshTrigger] = useState(0);
  // Bumped whenever the user picks a cwd via a quick action (e.g. command
  // palette). ChatInterface re-reads localStorage when this changes so the
  // selected cwd updates even if we're already on /new.
  const [cwdSyncTrigger, setCwdSyncTrigger] = useState(0);
  const [navigateUserMessageTrigger, setNavigateUserMessageTrigger] = useState(0);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  // Global ephemeral terminals - persist across conversation switches and
  // (via dtach sessions on the server) page reloads. We hydrate from the
  // server's terminal list on mount.
  const [ephemeralTerminals, setEphemeralTerminals] = useState<EphemeralTerminal[]>([]);

  useEffect(() => {
    let cancelled = false;
    fetch("/api/terminals")
      .then((r) => (r.ok ? r.json() : []))
      .then((rows: Array<{ id: string; command: string; cwd: string; created_at: string }>) => {
        if (cancelled || !Array.isArray(rows) || rows.length === 0) return;
        setEphemeralTerminals((prev) => {
          const have = new Set(prev.map((t) => t.termId).filter(Boolean));
          const restored: EphemeralTerminal[] = rows
            .filter((r) => !have.has(r.id))
            .map((r) => ({
              id: r.id,
              termId: r.id,
              command: r.command,
              cwd: r.cwd,
              createdAt: new Date(r.created_at || Date.now()),
            }));
          return [...restored, ...prev];
        });
      })
      .catch((err) => {
        console.warn("failed to fetch persistent terminals:", err);
      });
    return () => {
      cancelled = true;
    };
  }, []);

  const handleTerminalAttached = useCallback((id: string, termId: string) => {
    setEphemeralTerminals((prev) => prev.map((t) => (t.id === id ? { ...t, termId } : t)));
  }, []);

  const handleTerminalClose = useCallback((id: string) => {
    setEphemeralTerminals((prev) => {
      const t = prev.find((x) => x.id === id);
      if (t && t.termId) {
        // Best-effort: tell the server to kill the persistent session.
        fetch(`/api/terminals/${encodeURIComponent(t.termId)}`, { method: "DELETE" }).catch((err) =>
          console.warn("failed to delete terminal:", err),
        );
      }
      return prev.filter((x) => x.id !== id);
    });
  }, []);
  const [showActiveTrigger, setShowActiveTrigger] = useState(0);
  const initialSlugResolved = useRef(false);
  const conversationListHashRef = useRef<string | null>(null);
  const conversationsRef = useRef<ConversationWithState[]>([]);

  // Resolve initial slug from URL - uses the captured initialSlugFromUrl
  // Returns the conversation if found, null otherwise
  const resolveInitialSlug = useCallback(
    async (convs: Conversation[]): Promise<Conversation | null> => {
      if (initialSlugResolved.current) return null;
      initialSlugResolved.current = true;

      const urlSlug = initialSlugFromUrl;
      if (!urlSlug) return null;

      // First check if we already have this conversation in our list
      const existingConv = convs.find((c) => c.slug === urlSlug);
      if (existingConv) return existingConv;

      // Otherwise, try to fetch by slug (may be a subagent)
      try {
        const conv = await api.getConversationBySlug(urlSlug);
        if (conv) return conv;
      } catch (err) {
        console.error("Failed to resolve slug:", err);
      }

      // Slug not found, clear the URL
      window.history.replaceState({}, "", "/");
      return null;
    },
    [],
  );

  // Load conversations on mount
  useEffect(() => {
    loadConversations();
  }, []);

  // The patch stream emits both top-level conversations and their subagents in
  // a single list so subagent state can be diffed inline. Anything that's
  // about the user-facing “conversation list” (navigation, default
  // selection) should ignore subagents.
  const topLevelConversations = useMemo(
    () => conversations.filter((c) => !c.parent_conversation_id),
    [conversations],
  );

  const navigateToNextConversation = useCallback(() => {
    if (topLevelConversations.length === 0) return;
    const currentIndex = topLevelConversations.findIndex(
      (c) => c.conversation_id === currentConversationId,
    );
    // Next = further down the list (older)
    const nextIndex =
      currentIndex < 0 ? 0 : Math.min(currentIndex + 1, topLevelConversations.length - 1);
    const next = topLevelConversations[nextIndex];
    setCurrentConversationId(next.conversation_id);
    setViewedConversation(next);
  }, [topLevelConversations, currentConversationId]);

  const navigateToPreviousConversation = useCallback(() => {
    if (topLevelConversations.length === 0) return;
    const currentIndex = topLevelConversations.findIndex(
      (c) => c.conversation_id === currentConversationId,
    );
    // Previous = further up the list (newer)
    const prevIndex = currentIndex < 0 ? 0 : Math.max(currentIndex - 1, 0);
    const prev = topLevelConversations[prevIndex];
    setCurrentConversationId(prev.conversation_id);
    setViewedConversation(prev);
  }, [topLevelConversations, currentConversationId]);

  const navigateToNextUserMessage = useCallback(() => {
    setNavigateUserMessageTrigger((prev) => Math.abs(prev) + 1);
  }, []);

  const navigateToPreviousUserMessage = useCallback(() => {
    setNavigateUserMessageTrigger((prev) => -(Math.abs(prev) + 1));
  }, []);

  // Global keyboard shortcuts (including Ctrl+M chord sequences)
  useEffect(() => {
    const isMac = navigator.platform.toUpperCase().includes("MAC");
    let chordPending = false;
    let chordTimer: number | null = null;

    const clearChord = () => {
      chordPending = false;
      if (chordTimer !== null) {
        clearTimeout(chordTimer);
        chordTimer = null;
      }
    };

    const handleKeyDown = (e: KeyboardEvent) => {
      // Handle second key of Ctrl+M chord (before the Mac Ctrl passthrough)
      if (chordPending) {
        clearChord();
        if (e.key === "n" || e.key === "N") {
          e.preventDefault();
          navigateToNextUserMessage();
          return;
        }
        if (e.key === "p" || e.key === "P") {
          e.preventDefault();
          navigateToPreviousUserMessage();
          return;
        }
        // Any other key cancels the chord
        return;
      }

      // Ctrl+M on all platforms: start chord sequence
      // (intentionally before the Mac Ctrl passthrough — we use Ctrl, not Cmd,
      // to avoid overriding Cmd+M which is system minimize on macOS)
      if (e.ctrlKey && !e.metaKey && !e.altKey && (e.key === "m" || e.key === "M")) {
        e.preventDefault();
        chordPending = true;
        // Auto-cancel chord after 1.5 seconds
        chordTimer = window.setTimeout(clearChord, 1500);
        return;
      }

      // On macOS: Ctrl+K is readline (kill to end of line), let it pass through
      if (isMac && e.ctrlKey && !e.metaKey) return;
      // On macOS use Cmd+K, on other platforms use Ctrl+K
      const modifierPressed = isMac ? e.metaKey : e.ctrlKey;

      if (modifierPressed && e.key === "k") {
        e.preventDefault();
        setCommandPaletteOpen((prev) => !prev);
        return;
      }

      // Alt+ArrowDown: next conversation
      if (e.altKey && !e.ctrlKey && !e.metaKey && !e.shiftKey && e.key === "ArrowDown") {
        e.preventDefault();
        navigateToNextConversation();
        return;
      }

      // Alt+ArrowUp: previous conversation
      if (e.altKey && !e.ctrlKey && !e.metaKey && !e.shiftKey && e.key === "ArrowUp") {
        e.preventDefault();
        navigateToPreviousConversation();
        return;
      }
    };
    document.addEventListener("keydown", handleKeyDown);
    return () => {
      document.removeEventListener("keydown", handleKeyDown);
      clearChord();
    };
  }, [
    navigateToNextConversation,
    navigateToPreviousConversation,
    navigateToNextUserMessage,
    navigateToPreviousUserMessage,
  ]);

  // Handle popstate events (browser back/forward and SubagentTool navigation)
  useEffect(() => {
    const handlePopState = async () => {
      if (isNewPath()) {
        setCurrentConversationId(null);
        setViewedConversation(null);
        return;
      }
      const slug = getSlugFromPath();
      if (!slug) {
        return;
      }

      // Try to find in existing conversations first
      const existingConv = conversations.find((c) => c.slug === slug);
      if (existingConv) {
        setCurrentConversationId(existingConv.conversation_id);
        setViewedConversation(existingConv);
        return;
      }

      // Otherwise fetch by slug (may be a subagent)
      try {
        const conv = await api.getConversationBySlug(slug);
        if (conv) {
          setCurrentConversationId(conv.conversation_id);
          setViewedConversation(conv);
        }
      } catch (err) {
        console.error("Failed to navigate to conversation:", err);
      }
    };

    window.addEventListener("popstate", handlePopState);
    return () => window.removeEventListener("popstate", handlePopState);
  }, [conversations]);

  useEffect(() => {
    conversationsRef.current = conversations;
  }, [conversations]);

  const syncConversations = useCallback(
    (updater: (prev: ConversationWithState[]) => ConversationWithState[]) => {
      setConversations((prev) => {
        const next = updater(prev);
        conversationsRef.current = next;
        return next;
      });
    },
    [],
  );

  const handleConversationListPatch = useCallback(
    (event: ConversationListPatchEvent) => {
      const currentHash = conversationListHashRef.current;
      if (!event.reset && event.old_hash !== currentHash) {
        return;
      }
      syncConversations((prev) => {
        const next = applyConversationListPatch(prev, event.patch);
        const nextIds = new Set(next.map((conv) => conv.conversation_id));
        for (const conv of prev) {
          if (!nextIds.has(conv.conversation_id)) {
            conversationCache.delete(conv.conversation_id);
          }
        }
        return next;
      });
      conversationListHashRef.current = event.new_hash;
    },
    [syncConversations],
  );

  // Open the standalone list-only stream only when no conversation is
  // selected. When one is selected, ChatInterface opens the combined stream
  // (messages + list patches) so the UI never holds more than one
  // subscription at a time.
  useEffect(() => {
    if (currentConversationId) return;
    const stream = connectConversationListStream({
      getHash: () => conversationListHashRef.current,
      onPatch: handleConversationListPatch,
      onStatusChange: (status) => {
        if (status !== "connected") {
          console.warn(`Conversation list stream ${status}`);
        }
      },
    });
    return () => stream.close();
  }, [currentConversationId, handleConversationListPatch]);

  // Update page title and URL when conversation changes
  useEffect(() => {
    // Use viewedConversation if it matches (handles subagents), otherwise look up from list
    const currentConv =
      viewedConversation?.conversation_id === currentConversationId
        ? viewedConversation
        : conversations.find((conv) => conv.conversation_id === currentConversationId);
    if (currentConv) {
      updatePageTitle(currentConv);
      updateUrlWithSlug(currentConv);
    }
  }, [currentConversationId, viewedConversation, conversations]);

  const loadConversations = async () => {
    try {
      setLoading(true);
      setError(null);
      const snapshot = await api.getConversationsSnapshot();
      const streamHash = conversationListHashRef.current;
      if (!streamHash) {
        syncConversations(() => snapshot.conversations);
        conversationListHashRef.current = snapshot.hash;
      }
      const currentList = streamHash ? conversationsRef.current : snapshot.conversations;
      const topLevel = currentList.filter((c) => !c.parent_conversation_id);

      // Try to resolve conversation from URL slug first (slug may match a
      // subagent, so search the full list).
      const slugConv = await resolveInitialSlug(currentList);
      if (slugConv) {
        setCurrentConversationId(slugConv.conversation_id);
        setViewedConversation(slugConv);
      } else if (!initialIsNew && topLevel.length > 0) {
        // No slug in URL and not on /new — select the most recent
        // top-level conversation.
        setCurrentConversationId(topLevel[0].conversation_id);
        setViewedConversation(topLevel[0]);
      }
    } catch (err) {
      console.error("Failed to load conversations:", err);
      setError("Failed to load conversations. Please refresh the page.");
    } finally {
      setLoading(false);
    }
  };

  const startNewConversation = () => {
    // Save the current conversation's cwd to localStorage so the new conversation picks it up
    if (currentConversation?.cwd) {
      localStorage.setItem("shelley_selected_cwd", currentConversation.cwd);
    }
    // Clear the current conversation - a new one will be created when the user sends their first message
    setCurrentConversationId(null);
    setViewedConversation(null);
    // Clear URL when starting new conversation
    window.history.replaceState({}, "", "/");
    setDrawerOpen(false);
  };

  const startNewConversationWithCwd = (cwd: string) => {
    localStorage.setItem("shelley_selected_cwd", cwd);
    setCurrentConversationId(null);
    setViewedConversation(null);
    window.history.replaceState({}, "", "/");
    setDrawerOpen(false);
    // Force ChatInterface to re-read the cwd from localStorage even if it's
    // already mounted in the new-conversation view.
    setCwdSyncTrigger((n) => n + 1);
  };

  const selectConversation = (conversation: Conversation) => {
    setCurrentConversationId(conversation.conversation_id);
    setViewedConversation(conversation);
    setDrawerOpen(false);
  };

  const toggleDrawerCollapsed = () => {
    setDrawerCollapsed((prev) => !prev);
  };

  const updateConversation = (updatedConversation: Conversation) => {
    // The top-level conversation list is owned by the patch stream; keep the
    // currently viewed metadata fresh without changing that list out-of-band.
    if (updatedConversation.conversation_id === currentConversationId) {
      setViewedConversation(updatedConversation);
    }
  };

  const handleConversationArchived = (conversationId: string) => {
    conversationCache.delete(conversationId);
    // If the archived conversation was current, switch immediately; the patch
    // stream will remove it from the list.
    if (currentConversationId === conversationId) {
      const remaining = conversationsRef.current.filter(
        (conv) => conv.conversation_id !== conversationId && !conv.parent_conversation_id,
      );
      setCurrentConversationId(remaining.length > 0 ? remaining[0].conversation_id : null);
      setViewedConversation(remaining.length > 0 ? remaining[0] : null);
    }
  };

  const handleConversationUnarchived = (conversation: Conversation) => {
    // The conversation list patch stream will add it back to the active list.
    // Update viewedConversation so archived state reflects immediately
    if (conversation.conversation_id === currentConversationId) {
      setViewedConversation(conversation);
    }
    // Switch drawer back to active conversations view
    setShowActiveTrigger((prev) => prev + 1);
  };

  const handleConversationRenamed = (conversation: Conversation) => {
    if (conversation.conversation_id === currentConversationId) {
      setViewedConversation(conversation);
    }
  };

  if (loading && conversations.length === 0) {
    return (
      <div className="loading-container">
        <div className="loading-content">
          <div className="spinner" style={{ margin: "0 auto 1rem" }}></div>
          <p className="text-secondary">{t("loading")}</p>
        </div>
      </div>
    );
  }

  if (error && conversations.length === 0) {
    return (
      <div className="error-container">
        <div className="error-content">
          <p className="error-message" style={{ marginBottom: "1rem" }}>
            {error}
          </p>
          <button onClick={loadConversations} className="btn-primary">
            {t("retry")}
          </button>
        </div>
      </div>
    );
  }

  const currentConversation =
    conversations.find((conv) => conv.conversation_id === currentConversationId) ||
    (viewedConversation?.conversation_id === currentConversationId
      ? { ...viewedConversation, working: false, subagent_count: 0 }
      : undefined);

  // Get the CWD from the current conversation, or fall back to the most recent conversation
  const mostRecentCwd =
    currentConversation?.cwd ||
    (topLevelConversations.length > 0 ? topLevelConversations[0].cwd : null);

  const handleFirstMessage = async (
    message: string,
    model: string,
    cwd?: string,
    conversationType?: "normal" | "orchestrator",
    subagentBackend?: "shelley" | "claude-cli" | "codex-cli",
    toolOverrides?: Record<string, "on" | "off">,
  ) => {
    try {
      const hasOverrides = toolOverrides && Object.keys(toolOverrides).length > 0;
      const convOpts =
        conversationType === "orchestrator" || hasOverrides
          ? {
              ...(conversationType === "orchestrator"
                ? { type: "orchestrator" as const, subagent_backend: subagentBackend || "shelley" }
                : {}),
              ...(hasOverrides ? { tool_overrides: toolOverrides } : {}),
            }
          : undefined;
      const response = await api.sendMessageWithNewConversation({
        message,
        model,
        cwd,
        conversation_options: convOpts,
      });
      const newConversationId = response.conversation_id;

      setCurrentConversationId(newConversationId);
    } catch (err) {
      console.error("Failed to send first message:", err);
      setError(err instanceof Error ? err.message : "Failed to send message");
      throw err;
    }
  };

  const handleDistillNewGeneration = async (
    sourceConversationId: string,
    model: string,
    cwd?: string,
  ) => {
    try {
      await api.distillNewGeneration(sourceConversationId, model, cwd);
      const updatedConvs = await api.getConversations();
      setConversations(updatedConvs);
      setCurrentConversationId(sourceConversationId);
    } catch (err) {
      console.error("Failed to distill into new generation:", err);
      setError("Failed to distill into new generation");
      throw err;
    }
  };

  return (
    <WorkerPoolContextProvider
      poolOptions={diffsPoolOptions}
      highlighterOptions={diffsHighlighterOptions}
    >
      <div className="app-container">
        <ConversationDrawer
          isOpen={drawerOpen}
          isCollapsed={drawerCollapsed}
          onClose={() => setDrawerOpen(false)}
          onToggleCollapse={toggleDrawerCollapsed}
          conversations={conversations}
          currentConversationId={currentConversationId}
          viewedConversation={viewedConversation}
          onSelectConversation={selectConversation}
          onNewConversation={startNewConversation}
          onConversationArchived={handleConversationArchived}
          onConversationUnarchived={handleConversationUnarchived}
          onConversationRenamed={handleConversationRenamed}
          showActiveTrigger={showActiveTrigger}
        />

        {/* Main content: Chat interface */}
        <div className="main-content">
          <ChatInterface
            conversationId={currentConversationId}
            onOpenDrawer={() => setDrawerOpen(true)}
            onNewConversation={startNewConversation}
            onArchiveConversation={async (conversationId: string) => {
              await api.archiveConversation(conversationId);
              handleConversationArchived(conversationId);
            }}
            currentConversation={currentConversation}
            onConversationUpdate={updateConversation}
            conversationListHash={conversationListHashRef.current}
            onConversationListPatch={handleConversationListPatch}
            onFirstMessage={handleFirstMessage}
            onDistillNewGeneration={handleDistillNewGeneration}
            mostRecentCwd={mostRecentCwd}
            isDrawerCollapsed={drawerCollapsed}
            onToggleDrawerCollapse={toggleDrawerCollapsed}
            openDiffViewerTrigger={diffViewerTrigger}
            openGitGraphTrigger={gitGraphTrigger}
            modelsRefreshTrigger={modelsRefreshTrigger}
            cwdSyncTrigger={cwdSyncTrigger}
            onOpenModelsModal={() => setModelsModalOpen(true)}
            ephemeralTerminals={ephemeralTerminals}
            setEphemeralTerminals={setEphemeralTerminals}
            onTerminalAttached={handleTerminalAttached}
            onTerminalClose={handleTerminalClose}
            navigateUserMessageTrigger={navigateUserMessageTrigger}
            onConversationUnarchived={handleConversationUnarchived}
          />
        </div>

        {/* Command Palette */}
        <CommandPalette
          isOpen={commandPaletteOpen}
          onClose={() => setCommandPaletteOpen(false)}
          conversations={topLevelConversations}
          currentConversation={currentConversation || null}
          onNewConversation={() => {
            startNewConversation();
            setCommandPaletteOpen(false);
          }}
          onNewConversationWithCwd={(cwd: string) => {
            startNewConversationWithCwd(cwd);
            setCommandPaletteOpen(false);
          }}
          onSelectConversation={(conversation) => {
            selectConversation(conversation);
            setCommandPaletteOpen(false);
          }}
          onArchiveConversation={async (conversationId: string) => {
            try {
              await api.archiveConversation(conversationId);
              handleConversationArchived(conversationId);
            } catch (err) {
              console.error("Failed to archive conversation:", err);
            }
          }}
          onOpenDiffViewer={() => {
            setDiffViewerTrigger((prev) => prev + 1);
            setCommandPaletteOpen(false);
          }}
          onOpenGitGraph={() => {
            setGitGraphTrigger((prev) => prev + 1);
            setCommandPaletteOpen(false);
          }}
          onOpenModelsModal={() => {
            setModelsModalOpen(true);
            setCommandPaletteOpen(false);
          }}
          onOpenNotificationsModal={() => {
            setNotificationsModalOpen(true);
            setCommandPaletteOpen(false);
          }}
          onNextConversation={navigateToNextConversation}
          onPreviousConversation={navigateToPreviousConversation}
          onNextUserMessage={navigateToNextUserMessage}
          onPreviousUserMessage={navigateToPreviousUserMessage}
          hasCwd={
            !!(
              currentConversation?.cwd ||
              mostRecentCwd ||
              localStorage.getItem("shelley_selected_cwd") ||
              window.__SHELLEY_INIT__?.default_cwd
            )
          }
        />

        <ModelsModal
          isOpen={modelsModalOpen}
          onClose={() => setModelsModalOpen(false)}
          onModelsChanged={() => setModelsRefreshTrigger((prev) => prev + 1)}
        />

        <NotificationsModal
          isOpen={notificationsModalOpen}
          onClose={() => setNotificationsModalOpen(false)}
        />

        {/* Backdrop for mobile drawer */}
        {drawerOpen && (
          <div className="backdrop hide-on-desktop" onClick={() => setDrawerOpen(false)} />
        )}
      </div>
    </WorkerPoolContextProvider>
  );
}

export default App;
