// ui/src/components/ConfigFieldInput.tsx
import React from "react";

interface ConfigField {
  name: string;
  label: string;
  type: string;
  required: boolean;
  placeholder?: string;
  description?: string;
  options?: string[];
}

interface ConfigFieldInputProps {
  field: ConfigField;
  value: string;
  onChange: (value: string) => void;
}

export default function ConfigFieldInput({ field, value, onChange }: ConfigFieldInputProps) {
  const inputId = `config-${field.name}`;
  const descId = `${inputId}-desc`;

  return (
    <div className="form-group">
      <label htmlFor={inputId}>
        {field.label}
        {field.required && " *"}
      </label>
      {field.options && field.options.length > 0 ? (
        <select
          id={inputId}
          className="form-input"
          value={value}
          onChange={(e) => onChange(e.target.value)}
          aria-describedby={field.description ? descId : undefined}
        >
          <option value="">Select...</option>
          {field.options.map((opt) => (
            <option key={opt} value={opt}>
              {opt}
            </option>
          ))}
        </select>
      ) : (
        <input
          id={inputId}
          className="form-input"
          type={field.type === "password" ? "password" : "text"}
          value={value}
          onChange={(e) => onChange(e.target.value)}
          placeholder={field.placeholder}
          aria-describedby={field.description ? descId : undefined}
        />
      )}
      {field.description && (
        <span
          id={descId}
          style={{ fontSize: "0.75rem", color: "var(--text-secondary)", marginTop: "0.25rem", display: "block" }}
        >
          {field.description}
        </span>
      )}
    </div>
  );
}

// ui/src/vue/components/ConfigFieldInput.vue
<!-- Vue port of components/ConfigFieldInput.tsx. Generic config field renderer
     used by NotificationsModal. Preserves form-group / form-input classes,
     the `config-<name>` id, aria-describedby wiring and the
     config-field-description class. -->
<template>
  <div class="form-group">
    <label :for="inputId"> {{ field.label }}{{ field.required ? " *" : "" }} </label>
    <select
      v-if="field.options && field.options.length > 0"
      :id="inputId"
      class="form-input"
      :value="value"
      :aria-describedby="field.description ? descId : undefined"
      @change="emit('change', ($event.target as HTMLSelectElement).value)"
    >
      <option value="">Select...</option>
      <option v-for="opt in field.options" :key="opt" :value="opt">{{ opt }}</option>
    </select>
    <input
      v-else
      :id="inputId"
      class="form-input"
      :type="field.type === 'password' ? 'password' : 'text'"
      :value="value"
      :placeholder="field.placeholder"
      :aria-describedby="field.description ? descId : undefined"
      @input="emit('change', ($event.target as HTMLInputElement).value)"
    />
    <span v-if="field.description" :id="descId" class="config-field-description">
      {{ field.description }}
    </span>
  </div>
</template>

<script setup lang="ts">
import { computed } from "vue";

interface ConfigField {
  name: string;
  label: string;
  type: string;
  required: boolean;
  placeholder?: string;
  description?: string;
  options?: string[];
}

const props = defineProps<{
  field: ConfigField;
  value: string;
}>();
const emit = defineEmits<{ (e: "change", value: string): void }>();

const inputId = computed(() => `config-${props.field.name}`);
const descId = computed(() => `${inputId.value}-desc`);
</script>
