// ui/src/components/TerminalPanel.tsx
import React, { useEffect, useRef, useState, useCallback } from "react";
import { Terminal } from "@xterm/xterm";
import { FitAddon } from "@xterm/addon-fit";
import { WebLinksAddon } from "@xterm/addon-web-links";
import { isDarkModeActive } from "../services/theme";
import "@xterm/xterm/css/xterm.css";

function base64ToUint8Array(base64String: string): Uint8Array {
  // @ts-expect-error Uint8Array.fromBase64 is a newer API
  if (Uint8Array.fromBase64) {
    // @ts-expect-error Uint8Array.fromBase64 is a newer API
    return Uint8Array.fromBase64(base64String);
  }
  const binaryString = atob(base64String);
  return Uint8Array.from(binaryString, (char) => char.charCodeAt(0));
}

export interface EphemeralTerminal {
  id: string;
  command: string;
  cwd: string;
  createdAt: Date;
  // termId is the server-side dtach session id. Set once the websocket reports
  // "attached". When reconnecting to a known session, set this up front so the
  // websocket re-attaches rather than spawning a new session.
  termId?: string;
}

interface TerminalPanelProps {
  terminals: EphemeralTerminal[];
  onClose: (id: string) => void;
  onInsertIntoInput?: (text: string) => void;
  autoFocusId?: string | null;
  onAutoFocusConsumed?: () => void;
  onActiveTerminalExited?: () => void;
  // onAttached fires when the server tells us which persistent session id this
  // terminal landed on. Callers can persist the id to survive reloads.
  onAttached?: (id: string, termId: string) => void;
}

// Theme colors for xterm.js
function getTerminalTheme(isDark: boolean): Record<string, string> {
  if (isDark) {
    return {
      background: "#1a1b26",
      foreground: "#c0caf5",
      cursor: "#c0caf5",
      cursorAccent: "#1a1b26",
      selectionBackground: "#364a82",
      selectionForeground: "#c0caf5",
      black: "#32344a",
      red: "#f7768e",
      green: "#9ece6a",
      yellow: "#e0af68",
      blue: "#7aa2f7",
      magenta: "#ad8ee6",
      cyan: "#449dab",
      white: "#9699a8",
      brightBlack: "#444b6a",
      brightRed: "#ff7a93",
      brightGreen: "#b9f27c",
      brightYellow: "#ff9e64",
      brightBlue: "#7da6ff",
      brightMagenta: "#bb9af7",
      brightCyan: "#0db9d7",
      brightWhite: "#acb0d0",
    };
  }
  return {
    background: "#f8f9fa",
    foreground: "#383a42",
    cursor: "#526eff",
    cursorAccent: "#f8f9fa",
    selectionBackground: "#bfceff",
    selectionForeground: "#383a42",
    black: "#383a42",
    red: "#e45649",
    green: "#50a14f",
    yellow: "#c18401",
    blue: "#4078f2",
    magenta: "#a626a4",
    cyan: "#0184bc",
    white: "#a0a1a7",
    brightBlack: "#4f525e",
    brightRed: "#e06c75",
    brightGreen: "#98c379",
    brightYellow: "#e5c07b",
    brightBlue: "#61afef",
    brightMagenta: "#c678dd",
    brightCyan: "#56b6c2",
    brightWhite: "#ffffff",
  };
}

type TermStatus = "connecting" | "running" | "exited" | "error";

// SVG icons
const CopyIcon = () => (
  <svg
    width="14"
    height="14"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
  >
    <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
    <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
  </svg>
);

const CopyAllIcon = () => (
  <svg
    width="14"
    height="14"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
  >
    <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
    <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
    <line x1="12" y1="17" x2="18" y2="17" />
  </svg>
);

const InsertIcon = () => (
  <svg
    width="14"
    height="14"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
  >
    <path d="M12 3v12" />
    <path d="m8 11 4 4 4-4" />
    <path d="M4 21h16" />
  </svg>
);

const InsertAllIcon = () => (
  <svg
    width="14"
    height="14"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
  >
    <path d="M12 3v12" />
    <path d="m8 11 4 4 4-4" />
    <path d="M4 21h16" />
    <line x1="4" y1="18" x2="20" y2="18" />
  </svg>
);

const CheckIcon = () => (
  <svg
    width="14"
    height="14"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
  >
    <polyline points="20 6 9 17 4 12" />
  </svg>
);

const CloseIcon = () => (
  <svg
    width="14"
    height="14"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
  >
    <line x1="18" y1="6" x2="6" y2="18" />
    <line x1="6" y1="6" x2="18" y2="18" />
  </svg>
);

const ChevronUpIcon = () => (
  <svg
    width="14"
    height="14"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
  >
    <polyline points="18 15 12 9 6 15" />
  </svg>
);

const ChevronDownIcon = () => (
  <svg
    width="14"
    height="14"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
  >
    <polyline points="6 9 12 15 18 9" />
  </svg>
);

function ActionButton({
  onClick,
  title,
  children,
  feedback,
}: {
  onClick: () => void;
  title: string;
  children: React.ReactNode;
  feedback?: boolean;
}) {
  return (
    <button
      onClick={onClick}
      title={title}
      className={`terminal-panel-action-btn${feedback ? " terminal-panel-action-btn-feedback" : ""}`}
    >
      {children}
    </button>
  );
}

export default function TerminalPanel({
  terminals,
  onClose,
  onInsertIntoInput,
  autoFocusId,
  onAutoFocusConsumed,
  onActiveTerminalExited,
  onAttached,
}: TerminalPanelProps) {
  const [activeTabId, setActiveTabId] = useState<string | null>(null);
  const [height, setHeight] = useState(300);
  const [minimized, setMinimized] = useState(false);
  const [copyFeedback, setCopyFeedback] = useState<string | null>(null);
  const [statusMap, setStatusMap] = useState<
    Map<string, { status: TermStatus; exitCode: number | null }>
  >(new Map());
  const isResizingRef = useRef(false);
  const startYRef = useRef(0);
  const startHeightRef = useRef(0);

  // Detect dark mode
  const [isDark, setIsDark] = useState(isDarkModeActive);

  useEffect(() => {
    const observer = new MutationObserver(() => {
      setIsDark(isDarkModeActive());
    });
    observer.observe(document.documentElement, {
      attributes: true,
      attributeFilter: ["class"],
    });
    return () => observer.disconnect();
  }, []);

  // Auto-select newest tab when a new terminal is added
  useEffect(() => {
    if (terminals.length > 0) {
      const lastTerminal = terminals[terminals.length - 1];
      setActiveTabId(lastTerminal.id);
      setMinimized(false); // expand when a new terminal arrives
    } else {
      setActiveTabId(null);
    }
  }, [terminals.length]);

  // If active tab got closed, switch to the last remaining
  useEffect(() => {
    if (activeTabId && !terminals.find((t) => t.id === activeTabId)) {
      if (terminals.length > 0) {
        setActiveTabId(terminals[terminals.length - 1].id);
      } else {
        setActiveTabId(null);
      }
    }
  }, [terminals, activeTabId]);

  const handleStatusChange = useCallback(
    (id: string, status: TermStatus, exitCode: number | null) => {
      setStatusMap((prev) => {
        const next = new Map(prev);
        const existing = next.get(id);
        // Don't overwrite exit status with ws.onclose
        if (existing && existing.status === "exited" && status === "exited") {
          return prev;
        }
        next.set(id, {
          status,
          exitCode: exitCode ?? existing?.exitCode ?? null,
        });
        return next;
      });
    },
    [],
  );

  // Resize drag
  const handleResizeMouseDown = useCallback(
    (e: React.MouseEvent) => {
      e.preventDefault();
      isResizingRef.current = true;
      startYRef.current = e.clientY;
      startHeightRef.current = height;

      const handleMouseMove = (e: MouseEvent) => {
        if (!isResizingRef.current) return;
        // Dragging up increases height
        const delta = startYRef.current - e.clientY;
        setHeight(Math.max(80, Math.min(800, startHeightRef.current + delta)));
      };

      const handleMouseUp = () => {
        isResizingRef.current = false;
        document.removeEventListener("mousemove", handleMouseMove);
        document.removeEventListener("mouseup", handleMouseUp);
      };

      document.addEventListener("mousemove", handleMouseMove);
      document.addEventListener("mouseup", handleMouseUp);
    },
    [height],
  );

  const showFeedback = useCallback((type: string) => {
    setCopyFeedback(type);
    setTimeout(() => setCopyFeedback(null), 1500);
  }, []);

  // Get the xterm instance for the active tab
  const xtermRegistryRef = useRef<Map<string, Terminal>>(new Map());

  const registerXterm = useCallback((id: string, xterm: Terminal) => {
    xtermRegistryRef.current.set(id, xterm);
  }, []);

  const unregisterXterm = useCallback((id: string) => {
    xtermRegistryRef.current.delete(id);
  }, []);

  // Auto-focus terminal when autoFocusId is set (e.g., for interactive shells)
  useEffect(() => {
    if (!autoFocusId) return;
    let cancelled = false;
    let timer: ReturnType<typeof setTimeout>;
    let attempt = 0;
    const tryFocus = () => {
      if (cancelled) return;
      const xterm = xtermRegistryRef.current.get(autoFocusId);
      if (xterm) {
        setActiveTabId(autoFocusId);
        setMinimized(false); // expand when focusing a terminal
        // Double-rAF to ensure we're past any keyup/form events that might steal focus
        requestAnimationFrame(() => {
          requestAnimationFrame(() => {
            xterm.focus();
          });
        });
        onAutoFocusConsumed?.();
        return;
      }
      if (++attempt < 10) {
        timer = setTimeout(tryFocus, 50);
      }
    };
    // Small initial delay to let the form submit / keyup events settle
    timer = setTimeout(tryFocus, 50);
    return () => {
      cancelled = true;
      clearTimeout(timer);
    };
  }, [autoFocusId, onAutoFocusConsumed]);

  // Restore focus to message input when the active terminal exits
  const prevActiveStatusRef = useRef<{ tabId: string | null; status: TermStatus | undefined }>({
    tabId: null,
    status: undefined,
  });
  useEffect(() => {
    if (!activeTabId || !onActiveTerminalExited) return;
    const info = statusMap.get(activeTabId);
    const prev = prevActiveStatusRef.current;
    // Only trigger on status transition within the same tab
    const wasRunning = prev.tabId === activeTabId && prev.status === "running";
    prevActiveStatusRef.current = { tabId: activeTabId, status: info?.status };
    if (wasRunning && (info?.status === "exited" || info?.status === "error")) {
      onActiveTerminalExited();
    }
  }, [activeTabId, statusMap, onActiveTerminalExited]);

  const getBufferText = useCallback(
    (mode: "screen" | "all"): string => {
      if (!activeTabId) return "";
      const xterm = xtermRegistryRef.current.get(activeTabId);
      if (!xterm) return "";

      const lines: string[] = [];
      const buffer = xterm.buffer.active;

      if (mode === "screen") {
        const startRow = buffer.viewportY;
        for (let i = 0; i < xterm.rows; i++) {
          const line = buffer.getLine(startRow + i);
          if (line) lines.push(line.translateToString(true));
        }
      } else {
        for (let i = 0; i < buffer.length; i++) {
          const line = buffer.getLine(i);
          if (line) lines.push(line.translateToString(true));
        }
      }
      return lines.join("\n").trimEnd();
    },
    [activeTabId],
  );

  const copyScreen = useCallback(() => {
    navigator.clipboard.writeText(getBufferText("screen"));
    showFeedback("copyScreen");
  }, [getBufferText, showFeedback]);

  const copyAll = useCallback(() => {
    navigator.clipboard.writeText(getBufferText("all"));
    showFeedback("copyAll");
  }, [getBufferText, showFeedback]);

  const insertScreen = useCallback(() => {
    if (onInsertIntoInput) {
      onInsertIntoInput(getBufferText("screen"));
      showFeedback("insertScreen");
    }
  }, [getBufferText, onInsertIntoInput, showFeedback]);

  const insertAll = useCallback(() => {
    if (onInsertIntoInput) {
      onInsertIntoInput(getBufferText("all"));
      showFeedback("insertAll");
    }
  }, [getBufferText, onInsertIntoInput, showFeedback]);

  const handleCloseActive = useCallback(() => {
    if (activeTabId) onClose(activeTabId);
  }, [activeTabId, onClose]);

  const toggleMinimized = useCallback(() => {
    setMinimized((prev) => !prev);
  }, []);

  // Refit terminals when un-minimizing by nudging the container to trigger ResizeObserver
  const wasMinimizedRef = useRef(minimized);
  useEffect(() => {
    const wasMinimized = wasMinimizedRef.current;
    wasMinimizedRef.current = minimized;
    if (wasMinimized && !minimized && activeTabId) {
      const timer = setTimeout(() => {
        const el = document.querySelector(`[data-terminal-id="${activeTabId}"]`);
        if (el) {
          (el as HTMLElement).style.height = "99.9%";
          requestAnimationFrame(() => {
            (el as HTMLElement).style.height = "100%";
          });
        }
      }, 30);
      return () => clearTimeout(timer);
    }
  }, [minimized, activeTabId]);

  if (terminals.length === 0) return null;

  // Truncate command for tab label
  const tabLabel = (cmd: string) => {
    // Show first word or first 30 chars
    const firstWord = cmd.split(/\s+/)[0];
    if (firstWord.length > 30) return firstWord.substring(0, 27) + "...";
    return firstWord;
  };

  return (
    <div
      className={`terminal-panel${minimized ? " terminal-panel-minimized" : ""}`}
      style={minimized ? undefined : { height: `${height}px`, flexShrink: 0 }}
    >
      {/* Resize handle at top — hidden when minimized */}
      {!minimized && (
        <div className="terminal-panel-resize-handle" onMouseDown={handleResizeMouseDown}>
          <div className="terminal-panel-resize-grip" />
        </div>
      )}

      {/* Tab bar + actions */}
      <div className="terminal-panel-header">
        {/* Minimize/maximize toggle */}
        <ActionButton
          onClick={toggleMinimized}
          title={minimized ? "Expand terminals" : "Minimize terminals"}
        >
          {minimized ? <ChevronUpIcon /> : <ChevronDownIcon />}
        </ActionButton>

        <div className="terminal-panel-tabs">
          {terminals.map((t) => {
            const info = statusMap.get(t.id);
            const isActive = t.id === activeTabId;
            return (
              <div
                key={t.id}
                className={`terminal-panel-tab${isActive ? " terminal-panel-tab-active" : ""}`}
                onClick={() => {
                  setActiveTabId(t.id);
                  if (minimized) setMinimized(false);
                }}
                title={t.command}
              >
                {info?.status === "running" && (
                  <span className="terminal-panel-tab-indicator terminal-panel-tab-running">●</span>
                )}
                {info?.status === "exited" && info.exitCode === 0 && (
                  <span className="terminal-panel-tab-indicator terminal-panel-tab-success">✓</span>
                )}
                {info?.status === "exited" && info.exitCode !== 0 && (
                  <span className="terminal-panel-tab-indicator terminal-panel-tab-error">✗</span>
                )}
                {info?.status === "error" && (
                  <span className="terminal-panel-tab-indicator terminal-panel-tab-error">✗</span>
                )}
                <span className="terminal-panel-tab-label">{tabLabel(t.command)}</span>
                <button
                  className="terminal-panel-tab-close"
                  onClick={(e) => {
                    e.stopPropagation();
                    onClose(t.id);
                  }}
                  title="Close terminal"
                >
                  ×
                </button>
              </div>
            );
          })}
        </div>

        {/* Action buttons — hidden when minimized */}
        {!minimized && (
          <div className="terminal-panel-actions">
            <ActionButton
              onClick={copyScreen}
              title="Copy visible screen"
              feedback={copyFeedback === "copyScreen"}
            >
              {copyFeedback === "copyScreen" ? <CheckIcon /> : <CopyIcon />}
            </ActionButton>
            <ActionButton
              onClick={copyAll}
              title="Copy all output"
              feedback={copyFeedback === "copyAll"}
            >
              {copyFeedback === "copyAll" ? <CheckIcon /> : <CopyAllIcon />}
            </ActionButton>
            {onInsertIntoInput && (
              <>
                <ActionButton
                  onClick={insertScreen}
                  title="Insert visible screen into input"
                  feedback={copyFeedback === "insertScreen"}
                >
                  {copyFeedback === "insertScreen" ? <CheckIcon /> : <InsertIcon />}
                </ActionButton>
                <ActionButton
                  onClick={insertAll}
                  title="Insert all output into input"
                  feedback={copyFeedback === "insertAll"}
                >
                  {copyFeedback === "insertAll" ? <CheckIcon /> : <InsertAllIcon />}
                </ActionButton>
              </>
            )}
            <div className="terminal-panel-actions-divider" />
            <ActionButton onClick={handleCloseActive} title="Close active terminal">
              <CloseIcon />
            </ActionButton>
          </div>
        )}
      </div>

      {/* Terminal content area — hidden (not unmounted) when minimized */}
      <div className="terminal-panel-content" style={minimized ? { display: "none" } : undefined}>
        {terminals.map((t) => (
          <TerminalInstanceWithRegistry
            key={t.id}
            term={t}
            isVisible={t.id === activeTabId}
            isDark={isDark}
            onStatusChange={handleStatusChange}
            onRegister={registerXterm}
            onUnregister={unregisterXterm}
            onAttached={onAttached}
          />
        ))}
      </div>
    </div>
  );
}

// Wrapper that also registers the xterm instance
function TerminalInstanceWithRegistry({
  term,
  isVisible,
  isDark,
  onStatusChange,
  onRegister,
  onUnregister,
  onAttached,
}: {
  term: EphemeralTerminal;
  isVisible: boolean;
  isDark: boolean;
  onStatusChange: (id: string, status: TermStatus, exitCode: number | null) => void;
  onRegister: (id: string, xterm: Terminal) => void;
  onUnregister: (id: string) => void;
  onAttached?: (id: string, termId: string) => void;
}) {
  const containerRef = useRef<HTMLDivElement>(null);
  const xtermRef = useRef<Terminal | null>(null);
  const fitAddonRef = useRef<FitAddon | null>(null);
  const wsRef = useRef<WebSocket | null>(null);

  useEffect(() => {
    if (!containerRef.current) return;

    const xterm = new Terminal({
      cursorBlink: true,
      fontSize: 14,
      fontFamily: 'Consolas, "Liberation Mono", Menlo, Courier, monospace',
      theme: getTerminalTheme(isDark),
      scrollback: 10000,
    });
    xtermRef.current = xterm;

    // Ensure control key combinations (like Ctrl-B for tmux) are passed
    // through to the terminal and not intercepted by the browser.
    xterm.attachCustomKeyEventHandler((e: KeyboardEvent) => {
      // Allow Ctrl+Shift+C / Ctrl+Shift+V for copy/paste
      if (e.ctrlKey && e.shiftKey && (e.key === "C" || e.key === "V")) {
        return false; // Let browser handle it
      }
      // For all Ctrl+<key> combos (e.g. Ctrl-B for tmux prefix),
      // prevent the browser default and let xterm handle it.
      if (e.ctrlKey && !e.shiftKey && !e.altKey && !e.metaKey && e.type === "keydown") {
        e.preventDefault();
        return true; // Let xterm process it
      }
      return true;
    });

    const fitAddon = new FitAddon();
    fitAddonRef.current = fitAddon;
    xterm.loadAddon(fitAddon);
    xterm.loadAddon(new WebLinksAddon());

    xterm.open(containerRef.current);
    fitAddon.fit();
    onRegister(term.id, xterm);

    const protocol = window.location.protocol === "https:" ? "wss:" : "ws:";
    // If we already have a persistent session id, reattach to it. Otherwise
    // spawn a new one by sending cmd+cwd.
    const params = new URLSearchParams();
    if (term.termId) {
      params.set("term_id", term.termId);
    }
    params.set("cmd", term.command);
    params.set("cwd", term.cwd);
    const wsUrl = `${protocol}//${window.location.host}/api/exec-ws?${params.toString()}`;
    const ws = new WebSocket(wsUrl);
    wsRef.current = ws;

    ws.onopen = () => {
      ws.send(JSON.stringify({ type: "init", cols: xterm.cols, rows: xterm.rows }));
      onStatusChange(term.id, "running", null);
    };

    ws.onmessage = (event) => {
      try {
        const msg = JSON.parse(event.data);
        if (msg.type === "output" && msg.data) {
          xterm.write(base64ToUint8Array(msg.data));
        } else if (msg.type === "attached" && msg.term_id) {
          onAttached?.(term.id, msg.term_id);
        } else if (msg.type === "exit") {
          const code = parseInt(msg.data, 10) || 0;
          onStatusChange(term.id, "exited", code);
        } else if (msg.type === "error") {
          xterm.write(`\r\n\x1b[31mError: ${msg.data}\x1b[0m\r\n`);
          onStatusChange(term.id, "error", null);
        }
      } catch (err) {
        console.error("Failed to parse terminal message:", err);
      }
    };

    ws.onerror = (event) => console.error("WebSocket error:", event);
    ws.onclose = () => {
      onStatusChange(term.id, "exited", null);
    };

    xterm.onData((data) => {
      if (ws.readyState === WebSocket.OPEN) {
        ws.send(JSON.stringify({ type: "input", data }));
      }
    });

    const ro = new ResizeObserver(() => {
      if (!fitAddonRef.current) return;
      fitAddonRef.current.fit();
      if (wsRef.current && wsRef.current.readyState === WebSocket.OPEN && xtermRef.current) {
        wsRef.current.send(
          JSON.stringify({
            type: "resize",
            cols: xtermRef.current.cols,
            rows: xtermRef.current.rows,
          }),
        );
      }
    });
    ro.observe(containerRef.current);

    return () => {
      ro.disconnect();
      ws.close();
      xterm.dispose();
      onUnregister(term.id);
    };
  }, [term.id, term.command, term.cwd]);

  // Update theme
  useEffect(() => {
    if (xtermRef.current) {
      xtermRef.current.options.theme = getTerminalTheme(isDark);
    }
  }, [isDark]);

  // Refit when visibility changes
  useEffect(() => {
    if (isVisible && fitAddonRef.current) {
      setTimeout(() => fitAddonRef.current?.fit(), 20);
    }
  }, [isVisible]);

  return (
    <div
      ref={containerRef}
      data-terminal-id={term.id}
      style={{
        width: "100%",
        height: "100%",
        display: isVisible ? "block" : "none",
        backgroundColor: isDark ? "#1a1b26" : "#f8f9fa",
      }}
    />
  );
}

// ui/src/vue/components/TerminalPanel.vue
<!-- Vue port of components/TerminalPanel.tsx. A bottom dock of ephemeral
     terminals backed by server-side dtach sessions (so they survive
     conversation switches + reloads). Preserves the .terminal-panel* class
     contract, the action-button titles, and the tab status indicators.

     The EphemeralTerminal type is re-exported here (from terminalTypes.ts) so
     other code can `import type { EphemeralTerminal } from
     "./components/TerminalPanel.vue"` exactly as it imported from the React
     module. The actual xterm.js + websocket lifecycle lives in the
     TerminalInstance.vue child (one per terminal).

     React callback props are mapped to emits:
       onClose                -> emit("close", id)
       onInsertIntoInput      -> emit("insert-into-input", text)
       onAutoFocusConsumed    -> emit("auto-focus-consumed")
       onActiveTerminalExited -> emit("active-terminal-exited")
       onAttached             -> emit("attached", id, termId)
     The presence of an onInsertIntoInput handler in React (which gates the
     insert buttons) is mirrored by the required `canInsertIntoInput` prop. -->
<template>
  <div
    v-if="terminals.length > 0"
    :class="`terminal-panel${minimized ? ' terminal-panel-minimized' : ''}`"
    :style="minimized ? undefined : { height: `${height}px`, flexShrink: 0 }"
  >
    <!-- Resize handle at top — hidden when minimized -->
    <div v-if="!minimized" class="terminal-panel-resize-handle" @mousedown="handleResizeMouseDown">
      <div class="terminal-panel-resize-grip" />
    </div>

    <!-- Tab bar + actions -->
    <div class="terminal-panel-header">
      <!-- Minimize/maximize toggle -->
      <button
        class="terminal-panel-action-btn"
        :title="minimized ? 'Expand terminals' : 'Minimize terminals'"
        @click="toggleMinimized"
      >
        <ChevronUpIcon v-if="minimized" />
        <ChevronDownIcon v-else />
      </button>

      <div class="terminal-panel-tabs">
        <div
          v-for="t in terminals"
          :key="t.id"
          :class="`terminal-panel-tab${t.id === activeTabId ? ' terminal-panel-tab-active' : ''}`"
          :title="t.command"
          @click="onTabClick(t.id)"
        >
          <span
            v-if="statusMap.get(t.id)?.status === 'running'"
            class="terminal-panel-tab-indicator terminal-panel-tab-running"
            >●</span
          >
          <span
            v-if="statusMap.get(t.id)?.status === 'exited' && statusMap.get(t.id)?.exitCode === 0"
            class="terminal-panel-tab-indicator terminal-panel-tab-success"
            >✓</span
          >
          <span
            v-if="statusMap.get(t.id)?.status === 'exited' && statusMap.get(t.id)?.exitCode !== 0"
            class="terminal-panel-tab-indicator terminal-panel-tab-error"
            >✗</span
          >
          <span
            v-if="statusMap.get(t.id)?.status === 'error'"
            class="terminal-panel-tab-indicator terminal-panel-tab-error"
            >✗</span
          >
          <span class="terminal-panel-tab-label">{{ tabLabel(t.command) }}</span>
          <button
            class="terminal-panel-tab-close"
            title="Close terminal"
            @click.stop="emit('close', t.id)"
          >
            ×
          </button>
        </div>
      </div>

      <!-- Action buttons — hidden when minimized -->
      <div v-if="!minimized" class="terminal-panel-actions">
        <button
          :class="`terminal-panel-action-btn${copyFeedback === 'copyScreen' ? ' terminal-panel-action-btn-feedback' : ''}`"
          title="Copy visible screen"
          @click="copyScreen"
        >
          <CheckIcon v-if="copyFeedback === 'copyScreen'" />
          <CopyIcon v-else />
        </button>
        <button
          :class="`terminal-panel-action-btn${copyFeedback === 'copyAll' ? ' terminal-panel-action-btn-feedback' : ''}`"
          title="Copy all output"
          @click="copyAll"
        >
          <CheckIcon v-if="copyFeedback === 'copyAll'" />
          <CopyAllIcon v-else />
        </button>
        <template v-if="canInsertIntoInput">
          <button
            :class="`terminal-panel-action-btn${copyFeedback === 'insertScreen' ? ' terminal-panel-action-btn-feedback' : ''}`"
            title="Insert visible screen into input"
            @click="insertScreen"
          >
            <CheckIcon v-if="copyFeedback === 'insertScreen'" />
            <InsertIcon v-else />
          </button>
          <button
            :class="`terminal-panel-action-btn${copyFeedback === 'insertAll' ? ' terminal-panel-action-btn-feedback' : ''}`"
            title="Insert all output into input"
            @click="insertAll"
          >
            <CheckIcon v-if="copyFeedback === 'insertAll'" />
            <InsertAllIcon v-else />
          </button>
        </template>
        <div class="terminal-panel-actions-divider" />
        <button
          class="terminal-panel-action-btn"
          title="Close active terminal"
          @click="handleCloseActive"
        >
          <CloseIcon />
        </button>
      </div>
    </div>

    <!-- Terminal content area — hidden (not unmounted) when minimized -->
    <div class="terminal-panel-content" :style="minimized ? { display: 'none' } : undefined">
      <TerminalInstance
        v-for="t in terminals"
        :key="t.id"
        :term="t"
        :is-visible="t.id === activeTabId"
        :is-dark="isDark"
        :conversation-id="conversationId ?? null"
        :model="model ?? null"
        @status-change="handleStatusChange"
        @register="registerXterm"
        @unregister="unregisterXterm"
        @attached="(id, termId) => emit('attached', id, termId)"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import { onMounted, onUnmounted, ref, watch } from "vue";
import type { Terminal } from "@xterm/xterm";
import { isDarkModeActive } from "../../services/theme";
import TerminalInstance from "./TerminalInstance.vue";
import type { TermStatus } from "./terminalHelpers";
import type { EphemeralTerminal } from "./terminalTypes";
import CopyIcon from "./terminalIcons/CopyIcon.vue";
import CopyAllIcon from "./terminalIcons/CopyAllIcon.vue";
import InsertIcon from "./terminalIcons/InsertIcon.vue";
import InsertAllIcon from "./terminalIcons/InsertAllIcon.vue";
import CheckIcon from "./terminalIcons/CheckIcon.vue";
import CloseIcon from "./terminalIcons/CloseIcon.vue";
import ChevronUpIcon from "./terminalIcons/ChevronUpIcon.vue";
import ChevronDownIcon from "./terminalIcons/ChevronDownIcon.vue";

// Re-export EphemeralTerminal so importers can keep importing it from this
// module (the canonical definition lives in terminalTypes.ts).
export type { EphemeralTerminal } from "./terminalTypes";

const props = defineProps<{
  terminals: EphemeralTerminal[];
  autoFocusId?: string | null;
  // Mirrors the presence of React's onInsertIntoInput callback, which gates
  // the insert buttons. When false the insert actions are not rendered.
  canInsertIntoInput?: boolean;
  // Context surfaced to spawned sessions via SHELLEY_* env vars. Only used on
  // initial spawn; reattaches use the env baked in when the session was
  // created.
  conversationId?: string | null;
  model?: string | null;
}>();

const emit = defineEmits<{
  (e: "close", id: string): void;
  (e: "insert-into-input", text: string): void;
  (e: "auto-focus-consumed"): void;
  (e: "active-terminal-exited"): void;
  (e: "attached", id: string, termId: string): void;
}>();

const activeTabId = ref<string | null>(null);
const height = ref(300);
const minimized = ref(false);
const copyFeedback = ref<string | null>(null);
const statusMap = ref<Map<string, { status: TermStatus; exitCode: number | null }>>(new Map());
const isResizingRef = { current: false };
const startYRef = { current: 0 };
const startHeightRef = { current: 0 };

// Detect dark mode
const isDark = ref(isDarkModeActive());
let observer: MutationObserver | null = null;
onMounted(() => {
  observer = new MutationObserver(() => {
    isDark.value = isDarkModeActive();
  });
  observer.observe(document.documentElement, {
    attributes: true,
    attributeFilter: ["class"],
  });
});
onUnmounted(() => observer?.disconnect());

// Auto-select newest tab when a new terminal is added (React effect on
// [terminals.length]).
watch(
  () => props.terminals.length,
  (len) => {
    if (len > 0) {
      const lastTerminal = props.terminals[props.terminals.length - 1];
      activeTabId.value = lastTerminal.id;
      minimized.value = false; // expand when a new terminal arrives
    } else {
      activeTabId.value = null;
    }
  },
);

// If active tab got closed, switch to the last remaining (React effect on
// [terminals, activeTabId]).
watch(
  () => [props.terminals, activeTabId.value] as const,
  () => {
    if (activeTabId.value && !props.terminals.find((t) => t.id === activeTabId.value)) {
      if (props.terminals.length > 0) {
        activeTabId.value = props.terminals[props.terminals.length - 1].id;
      } else {
        activeTabId.value = null;
      }
    }
  },
);

function handleStatusChange(id: string, status: TermStatus, exitCode: number | null) {
  const prev = statusMap.value;
  const next = new Map(prev);
  const existing = next.get(id);
  // Don't overwrite exit status with ws.onclose
  if (existing && existing.status === "exited" && status === "exited") {
    return;
  }
  next.set(id, {
    status,
    exitCode: exitCode ?? existing?.exitCode ?? null,
  });
  statusMap.value = next;
}

// Resize drag
function handleResizeMouseDown(e: MouseEvent) {
  e.preventDefault();
  isResizingRef.current = true;
  startYRef.current = e.clientY;
  startHeightRef.current = height.value;

  const handleMouseMove = (ev: MouseEvent) => {
    if (!isResizingRef.current) return;
    // Dragging up increases height
    const delta = startYRef.current - ev.clientY;
    height.value = Math.max(80, Math.min(800, startHeightRef.current + delta));
  };

  const handleMouseUp = () => {
    isResizingRef.current = false;
    document.removeEventListener("mousemove", handleMouseMove);
    document.removeEventListener("mouseup", handleMouseUp);
  };

  document.addEventListener("mousemove", handleMouseMove);
  document.addEventListener("mouseup", handleMouseUp);
}

function showFeedback(type: string) {
  copyFeedback.value = type;
  setTimeout(() => (copyFeedback.value = null), 1500);
}

// Registry of xterm instances by terminal id.
const xtermRegistry = new Map<string, Terminal>();
function registerXterm(id: string, xterm: Terminal) {
  xtermRegistry.set(id, xterm);
}
function unregisterXterm(id: string) {
  xtermRegistry.delete(id);
}

// Auto-focus terminal when autoFocusId is set (React effect on
// [autoFocusId, onAutoFocusConsumed]).
watch(
  () => props.autoFocusId,
  (autoFocusId) => {
    if (!autoFocusId) return;
    let cancelled = false;
    let timer: ReturnType<typeof setTimeout>;
    let attempt = 0;
    const tryFocus = () => {
      if (cancelled) return;
      const xterm = xtermRegistry.get(autoFocusId);
      if (xterm) {
        activeTabId.value = autoFocusId;
        minimized.value = false; // expand when focusing a terminal
        // Double-rAF to ensure we're past any keyup/form events that might steal focus
        requestAnimationFrame(() => {
          requestAnimationFrame(() => {
            xterm.focus();
          });
        });
        emit("auto-focus-consumed");
        return;
      }
      if (++attempt < 10) {
        timer = setTimeout(tryFocus, 50);
      }
    };
    // Small initial delay to let the form submit / keyup events settle
    timer = setTimeout(tryFocus, 50);
    // Cleanup when autoFocusId changes again.
    const stop = watch(
      () => props.autoFocusId,
      () => {
        cancelled = true;
        clearTimeout(timer);
        stop();
      },
    );
  },
);

// Restore focus to message input when the active terminal exits (React effect
// on [activeTabId, statusMap, onActiveTerminalExited]).
const prevActiveStatusRef = {
  current: { tabId: null as string | null, status: undefined as TermStatus | undefined },
};
watch(
  () => [activeTabId.value, statusMap.value] as const,
  () => {
    if (!activeTabId.value) return;
    const info = statusMap.value.get(activeTabId.value);
    const prev = prevActiveStatusRef.current;
    // Only trigger on status transition within the same tab
    const wasRunning = prev.tabId === activeTabId.value && prev.status === "running";
    prevActiveStatusRef.current = { tabId: activeTabId.value, status: info?.status };
    if (wasRunning && (info?.status === "exited" || info?.status === "error")) {
      emit("active-terminal-exited");
    }
  },
);

function getBufferText(mode: "screen" | "all"): string {
  if (!activeTabId.value) return "";
  const xterm = xtermRegistry.get(activeTabId.value);
  if (!xterm) return "";

  const lines: string[] = [];
  const buffer = xterm.buffer.active;

  if (mode === "screen") {
    const startRow = buffer.viewportY;
    for (let i = 0; i < xterm.rows; i++) {
      const line = buffer.getLine(startRow + i);
      if (line) lines.push(line.translateToString(true));
    }
  } else {
    for (let i = 0; i < buffer.length; i++) {
      const line = buffer.getLine(i);
      if (line) lines.push(line.translateToString(true));
    }
  }
  return lines.join("\n").trimEnd();
}

function copyScreen() {
  navigator.clipboard.writeText(getBufferText("screen"));
  showFeedback("copyScreen");
}
function copyAll() {
  navigator.clipboard.writeText(getBufferText("all"));
  showFeedback("copyAll");
}
function insertScreen() {
  if (props.canInsertIntoInput) {
    emit("insert-into-input", getBufferText("screen"));
    showFeedback("insertScreen");
  }
}
function insertAll() {
  if (props.canInsertIntoInput) {
    emit("insert-into-input", getBufferText("all"));
    showFeedback("insertAll");
  }
}

function handleCloseActive() {
  if (activeTabId.value) emit("close", activeTabId.value);
}

function toggleMinimized() {
  minimized.value = !minimized.value;
}

function onTabClick(id: string) {
  activeTabId.value = id;
  if (minimized.value) minimized.value = false;
}

// Refit terminals when un-minimizing by nudging the container to trigger
// ResizeObserver (React effect on [minimized, activeTabId]).
const wasMinimizedRef = { current: minimized.value };
watch(
  () => [minimized.value, activeTabId.value] as const,
  () => {
    const wasMinimized = wasMinimizedRef.current;
    wasMinimizedRef.current = minimized.value;
    if (wasMinimized && !minimized.value && activeTabId.value) {
      const timer = setTimeout(() => {
        const el = document.querySelector(`[data-terminal-id="${activeTabId.value}"]`);
        if (el) {
          (el as HTMLElement).style.height = "99.9%";
          requestAnimationFrame(() => {
            (el as HTMLElement).style.height = "100%";
          });
        }
      }, 30);
      // No explicit cleanup needed; the timer is short-lived.
      void timer;
    }
  },
);

// Truncate command for tab label
function tabLabel(cmd: string): string {
  // Show first word or first 30 chars
  const firstWord = cmd.split(/\s+/)[0];
  if (firstWord.length > 30) return firstWord.substring(0, 27) + "...";
  return firstWord;
}
</script>
