// ui/src/components/VimToggle.tsx
import React from "react";
import { Button } from "@/components/ui/button";

interface VimToggleProps {
  enabled: boolean;
  onChange: (enabled: boolean) => void;
}

// Compact toggle for enabling Monaco's vim emulation. Desktop only - mobile
// users don't have a useful keyboard for vim, and the parent component
// decides whether to render this at all.
export default function VimToggle({ enabled, onChange }: VimToggleProps) {
  return (
    <Button
      type="button"
      size="sm"
      variant={enabled ? "default" : "outline"}
      onClick={() => onChange(!enabled)}
      title={enabled ? "Disable Vim mode" : "Enable Vim mode"}
      aria-pressed={enabled}
    >
      Vim
    </Button>
  );
}

// ui/src/vue/components/VimToggle.vue
<!-- Vue port of components/VimToggle.tsx. Compact toggle for Monaco's vim
     emulation. Preserves the .vim-toggle class, aria-pressed, and the
     title toggle. Desktop only - the parent decides whether to render it.
     Emits "change" with the new enabled value (React onChange prop). -->
<template>
  <button
    type="button"
    :class="`vim-toggle ${enabled ? 'active' : ''}`"
    :title="enabled ? 'Disable Vim mode' : 'Enable Vim mode'"
    :aria-pressed="enabled"
    @click="emit('change', !enabled)"
  >
    Vim
  </button>
</template>

<script setup lang="ts">
defineProps<{
  enabled: boolean;
}>();
const emit = defineEmits<{ (e: "change", enabled: boolean): void }>();
</script>
