// ui/src/components/BrowserProfileTool.tsx
import React, { useState } from "react";
import { LLMContent } from "../types";

interface BrowserProfileToolProps {
  toolInput?: unknown;
  isRunning?: boolean;
  toolResult?: LLMContent[];
  hasError?: boolean;
  executionTime?: string;
}

function BrowserProfileTool({
  toolInput,
  isRunning,
  toolResult,
  hasError,
  executionTime,
}: BrowserProfileToolProps) {
  const [isExpanded, setIsExpanded] = useState(false);
  const [copied, setCopied] = useState(false);

  const input =
    typeof toolInput === "object" && toolInput !== null
      ? (toolInput as { action?: string; categories?: string })
      : {};

  const action = input.action || "";

  const output =
    toolResult && toolResult.length > 0 && toolResult[0].Text ? toolResult[0].Text : "";

  const isComplete = !isRunning && toolResult !== undefined;

  // Detect file paths in output (for cpu_stop, trace_stop results)
  const filePathMatch = output.match(/([^\s]+\.json)/i);
  const savedFilePath = filePathMatch ? filePathMatch[1] : null;

  const summary = action || "profile";

  const handleCopyPath = (e: React.MouseEvent) => {
    e.stopPropagation();
    if (savedFilePath) {
      navigator.clipboard.writeText(savedFilePath).then(() => {
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
      });
    }
  };

  return (
    <div className="tool" data-testid={isComplete ? "tool-call-completed" : "tool-call-running"}>
      <div className="tool-header" onClick={() => setIsExpanded(!isExpanded)}>
        <div className="tool-summary">
          <span className={`tool-emoji ${isRunning ? "running" : ""}`}>📊</span>
          <span className="tool-command">{summary}</span>
          {isComplete && hasError && <span className="tool-error">✗</span>}
          {isComplete && !hasError && <span className="tool-success">✓</span>}
        </div>
        <button
          className="tool-toggle"
          aria-label={isExpanded ? "Collapse" : "Expand"}
          aria-expanded={isExpanded}
        >
          <svg
            width="12"
            height="12"
            viewBox="0 0 12 12"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
            className={`tool-chevron${isExpanded ? " tool-chevron-expanded" : ""}`}
          >
            <path
              d="M4.5 3L7.5 6L4.5 9"
              stroke="currentColor"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
            />
          </svg>
        </button>
      </div>

      {isExpanded && (
        <div className="tool-details">
          <div className="tool-section">
            <div className="tool-label">Action:</div>
            <pre className="tool-code">{action || "(none)"}</pre>
          </div>

          {input.categories && (
            <div className="tool-section">
              <div className="tool-label">Categories:</div>
              <pre className="tool-code">{input.categories}</pre>
            </div>
          )}

          {isComplete && output && (
            <div className="tool-section">
              <div className="tool-label">
                Output{hasError ? " (Error)" : ""}:
                {executionTime && <span className="tool-time">{executionTime}</span>}
              </div>
              <pre className={`tool-code ${hasError ? "error" : ""}`}>{output}</pre>
            </div>
          )}

          {isComplete && savedFilePath && !hasError && (
            <div className="tool-section">
              <div className="tool-label">Profile/Trace file:</div>
              <div className="profile-file-wrapper">
                <code className="profile-file-path">{savedFilePath}</code>
                <button onClick={handleCopyPath} className="profile-copy-button">
                  {copied ? "✓ Copied" : "📋 Copy path"}
                </button>
                {(action === "cpu_stop" || action === "trace_stop") && (
                  <a
                    href={`https://www.speedscope.app/#profileURL=${encodeURIComponent(window.location.origin + "/api/read?path=" + encodeURIComponent(savedFilePath))}`}
                    target="_blank"
                    rel="noopener noreferrer"
                    onClick={(e) => e.stopPropagation()}
                    className="profile-speedscope-link"
                  >
                    🔥 Open in Speedscope
                  </a>
                )}
              </div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

export default BrowserProfileTool;

// ui/src/vue/components/tools/BrowserProfileTool.vue
<!-- Vue port of components/BrowserProfileTool.tsx. Preserves the exact DOM
     classes, data-testid, and aria contracts the e2e tests rely on. -->
<template>
  <div class="tool" :data-testid="isComplete ? 'tool-call-completed' : 'tool-call-running'">
    <div class="tool-header" @click="isExpanded = !isExpanded">
      <div class="tool-summary">
        <span class="tool-emoji" :class="{ running: isRunning }">📊</span>
        <span class="tool-command ellipsis-start">{{ summary }}</span>
      </div>
      <button
        class="tool-toggle"
        :aria-label="isExpanded ? 'Collapse' : 'Expand'"
        :aria-expanded="isExpanded"
      >
        <ToolChevron :expanded="isExpanded" />
      </button>
    </div>

    <div v-if="isExpanded" class="tool-details">
      <RunningToolTime v-if="isRunning" :start-time="toolInvokedAt" />
      <div class="tool-section">
        <div class="tool-label">Action:</div>
        <pre class="tool-code">{{ action || "(none)" }}</pre>
      </div>

      <div v-if="input.categories" class="tool-section">
        <div class="tool-label">Categories:</div>
        <pre class="tool-code">{{ input.categories }}</pre>
      </div>

      <div v-if="isComplete && output" class="tool-section">
        <div class="tool-label">
          Output{{ hasError ? " (Error)" : "" }}:
          <span v-if="executionTime" class="tool-time">{{ executionTime }}</span>
        </div>
        <pre :class="`tool-code ${hasError ? 'error' : ''}`">{{ output }}</pre>
      </div>

      <div v-if="isComplete && savedFilePath && !hasError" class="tool-section">
        <div class="tool-label">Profile/Trace file:</div>
        <div class="profile-file-wrapper">
          <code class="profile-file-path">{{ savedFilePath }}</code>
          <button class="profile-copy-button" @click="handleCopyPath">
            {{ copied ? "✓ Copied" : "📋 Copy path" }}
          </button>
          <a
            v-if="action === 'cpu_stop' || action === 'trace_stop'"
            :href="speedscopeUrl"
            target="_blank"
            rel="noopener noreferrer"
            class="profile-speedscope-link"
            @click.stop
          >
            🔥 Open in Speedscope
          </a>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref } from "vue";
import type { LLMContent } from "../../../types";
import ToolChevron from "./ToolChevron.vue";
import RunningToolTime from "./RunningToolTime.vue";

interface ProfileInput {
  action?: string;
  categories?: string;
}

const props = defineProps<{
  toolInput?: unknown;
  isRunning?: boolean;
  toolInvokedAt?: string | null;
  toolResult?: LLMContent[];
  hasError?: boolean;
  executionTime?: string;
}>();

const isExpanded = ref(false);
const copied = ref(false);

const input = computed<ProfileInput>(() =>
  typeof props.toolInput === "object" && props.toolInput !== null
    ? (props.toolInput as ProfileInput)
    : {},
);

const action = computed(() => input.value.action || "");

const output = computed(() =>
  props.toolResult && props.toolResult.length > 0 && props.toolResult[0].Text
    ? props.toolResult[0].Text
    : "",
);

const isComplete = computed(() => !props.isRunning && props.toolResult !== undefined);

// Detect file paths in output (for cpu_stop, trace_stop results)
const savedFilePath = computed<string | null>(() => {
  const filePathMatch = output.value.match(/([^\s]+\.json)/i);
  return filePathMatch ? filePathMatch[1] : null;
});

const summary = computed(() => action.value || "profile");

const speedscopeUrl = computed(() =>
  savedFilePath.value
    ? `https://www.speedscope.app/#profileURL=${encodeURIComponent(window.location.origin + "/api/read?path=" + encodeURIComponent(savedFilePath.value))}`
    : "",
);

function handleCopyPath(e: MouseEvent) {
  e.stopPropagation();
  if (savedFilePath.value) {
    navigator.clipboard.writeText(savedFilePath.value).then(() => {
      copied.value = true;
      setTimeout(() => (copied.value = false), 2000);
    });
  }
}
</script>
