// ui/src/components/BrowserNetworkTool.tsx
import React from "react";
import { LLMContent } from "../types";
import { ToolCard, ToolSection, ToolCode, ToolStatusMark } from "./ToolCard";

interface BrowserNetworkToolProps {
  toolInput?: unknown;
  isRunning?: boolean;
  toolResult?: LLMContent[];
  hasError?: boolean;
  executionTime?: string;
}

function BrowserNetworkTool({
  toolInput,
  isRunning,
  toolResult,
  hasError,
  executionTime,
}: BrowserNetworkToolProps) {
  const input =
    typeof toolInput === "object" && toolInput !== null
      ? (toolInput as { action?: string; filter?: string; limit?: number })
      : {};

  const action = input.action || "";

  const output =
    toolResult && toolResult.length > 0 && toolResult[0].Text ? toolResult[0].Text : "";

  const isComplete = !isRunning && toolResult !== undefined;

  const summaryParts: string[] = [action];
  if (input.filter) summaryParts.push(`filter: ${input.filter}`);
  const summary = summaryParts.filter(Boolean).join(" ") || "network";

  return (
    <ToolCard
      emoji="📡"
      running={isRunning}
      complete={isComplete}
      title={summary}
      status={isComplete ? <ToolStatusMark error={hasError} /> : null}
    >
      <ToolSection label="Action:">
        <ToolCode>{action || "(none)"}</ToolCode>
      </ToolSection>

      {input.filter && (
        <ToolSection label="Filter:">
          <ToolCode>{input.filter}</ToolCode>
        </ToolSection>
      )}

      {input.limit !== undefined && (
        <ToolSection label="Limit:">
          <ToolCode>{input.limit}</ToolCode>
        </ToolSection>
      )}

      {isComplete && output && (
        <ToolSection
          label={
            <span className="flex items-center gap-2">
              <span>Output{hasError ? " (Error)" : ""}:</span>
              {executionTime && (
                <span className="text-muted-foreground">{executionTime}</span>
              )}
            </span>
          }
        >
          <ToolCode error={hasError}>{output}</ToolCode>
        </ToolSection>
      )}
    </ToolCard>
  );
}

export default BrowserNetworkTool;

// ui/src/vue/components/tools/BrowserNetworkTool.vue
<!-- Vue port of components/BrowserNetworkTool.tsx. Preserves the exact DOM
     classes, data-testid, and aria contracts the e2e tests rely on. -->
<template>
  <div class="tool" :data-testid="isComplete ? 'tool-call-completed' : 'tool-call-running'">
    <div class="tool-header" @click="isExpanded = !isExpanded">
      <div class="tool-summary">
        <span class="tool-emoji" :class="{ running: isRunning }">📡</span>
        <span class="tool-command ellipsis-start">{{ summary }}</span>
      </div>
      <button
        class="tool-toggle"
        :aria-label="isExpanded ? 'Collapse' : 'Expand'"
        :aria-expanded="isExpanded"
      >
        <ToolChevron :expanded="isExpanded" />
      </button>
    </div>

    <div v-if="isExpanded" class="tool-details">
      <RunningToolTime v-if="isRunning" :start-time="toolInvokedAt" />
      <div class="tool-section">
        <div class="tool-label">Action:</div>
        <pre class="tool-code">{{ action || "(none)" }}</pre>
      </div>

      <div v-if="input.filter" class="tool-section">
        <div class="tool-label">Filter:</div>
        <pre class="tool-code">{{ input.filter }}</pre>
      </div>

      <div v-if="input.limit !== undefined" class="tool-section">
        <div class="tool-label">Limit:</div>
        <pre class="tool-code">{{ input.limit }}</pre>
      </div>

      <div v-if="isComplete && output" class="tool-section">
        <div class="tool-label">
          Output{{ hasError ? " (Error)" : "" }}:
          <span v-if="executionTime" class="tool-time">{{ executionTime }}</span>
        </div>
        <pre :class="`tool-code ${hasError ? 'error' : ''}`">{{ output }}</pre>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref } from "vue";
import type { LLMContent } from "../../../types";
import ToolChevron from "./ToolChevron.vue";
import RunningToolTime from "./RunningToolTime.vue";

interface NetworkInput {
  action?: string;
  filter?: string;
  limit?: number;
}

const props = defineProps<{
  toolInput?: unknown;
  isRunning?: boolean;
  toolInvokedAt?: string | null;
  toolResult?: LLMContent[];
  hasError?: boolean;
  executionTime?: string;
}>();

const isExpanded = ref(false);

const input = computed<NetworkInput>(() =>
  typeof props.toolInput === "object" && props.toolInput !== null
    ? (props.toolInput as NetworkInput)
    : {},
);

const action = computed(() => input.value.action || "");

const output = computed(() =>
  props.toolResult && props.toolResult.length > 0 && props.toolResult[0].Text
    ? props.toolResult[0].Text
    : "",
);

const isComplete = computed(() => !props.isRunning && props.toolResult !== undefined);

const summary = computed(() => {
  const summaryParts: string[] = [action.value];
  if (input.value.filter) summaryParts.push(`filter: ${input.value.filter}`);
  return summaryParts.filter(Boolean).join(" ") || "network";
});
</script>
