// ui/src/components/BrowserEmulateTool.tsx
import React from "react";
import { LLMContent } from "../types";
import { ToolCard, ToolSection, ToolCode, ToolStatusMark } from "./ToolCard";

interface BrowserEmulateToolProps {
  toolInput?: unknown;
  isRunning?: boolean;
  toolResult?: LLMContent[];
  hasError?: boolean;
  executionTime?: string;
}

function BrowserEmulateTool({
  toolInput,
  isRunning,
  toolResult,
  hasError,
  executionTime,
}: BrowserEmulateToolProps) {
  const input =
    typeof toolInput === "object" && toolInput !== null
      ? (toolInput as {
          action?: string;
          device?: string;
          width?: number;
          height?: number;
          mobile?: boolean;
          touch?: boolean;
          device_scale_factor?: number;
          enabled?: boolean;
          media?: string;
        })
      : {};

  const action = input.action || "";
  const device = input.device || "";

  const output =
    toolResult && toolResult.length > 0 && toolResult[0].Text ? toolResult[0].Text : "";

  const isComplete = !isRunning && toolResult !== undefined;

  // Build compact summary
  const summaryParts: string[] = [action];
  if (device) summaryParts.push(device);
  if (input.width && input.height) summaryParts.push(`${input.width}×${input.height}`);
  if (input.media) summaryParts.push(input.media);
  if (input.enabled !== undefined) summaryParts.push(input.enabled ? "on" : "off");
  const summary = summaryParts.filter(Boolean).join(" ") || "emulate";

  return (
    <ToolCard
      emoji="📱"
      running={isRunning}
      complete={isComplete}
      title={summary}
      status={isComplete ? <ToolStatusMark error={hasError} /> : null}
    >
      <ToolSection label="Action:">
        <ToolCode>{action || "(none)"}</ToolCode>
      </ToolSection>

      {device && (
        <ToolSection label="Device:">
          <ToolCode>{device}</ToolCode>
        </ToolSection>
      )}

      {input.width !== undefined && input.height !== undefined && (
        <ToolSection label="Dimensions:">
          <ToolCode>
            {input.width} × {input.height}
          </ToolCode>
        </ToolSection>
      )}

      {input.media && (
        <ToolSection label="Media:">
          <ToolCode>{input.media}</ToolCode>
        </ToolSection>
      )}

      {isComplete && output && (
        <ToolSection
          label={
            <span className="flex items-center gap-2">
              <span>Output{hasError ? " (Error)" : ""}:</span>
              {executionTime && (
                <span className="text-muted-foreground">{executionTime}</span>
              )}
            </span>
          }
        >
          <ToolCode error={hasError}>{output}</ToolCode>
        </ToolSection>
      )}
    </ToolCard>
  );
}

export default BrowserEmulateTool;

// ui/src/vue/components/tools/BrowserEmulateTool.vue
<!-- Vue port of components/BrowserEmulateTool.tsx. Preserves the exact DOM
     classes, data-testid, and aria contracts the e2e tests rely on. -->
<template>
  <div class="tool" :data-testid="isComplete ? 'tool-call-completed' : 'tool-call-running'">
    <div class="tool-header" @click="isExpanded = !isExpanded">
      <div class="tool-summary">
        <span class="tool-emoji" :class="{ running: isRunning }">📱</span>
        <span class="tool-command ellipsis-start">{{ summary }}</span>
      </div>
      <button
        class="tool-toggle"
        :aria-label="isExpanded ? 'Collapse' : 'Expand'"
        :aria-expanded="isExpanded"
      >
        <ToolChevron :expanded="isExpanded" />
      </button>
    </div>

    <div v-if="isExpanded" class="tool-details">
      <RunningToolTime v-if="isRunning" :start-time="toolInvokedAt" />
      <div class="tool-section">
        <div class="tool-label">Action:</div>
        <pre class="tool-code">{{ action || "(none)" }}</pre>
      </div>

      <div v-if="device" class="tool-section">
        <div class="tool-label">Device:</div>
        <pre class="tool-code">{{ device }}</pre>
      </div>

      <div v-if="input.width !== undefined && input.height !== undefined" class="tool-section">
        <div class="tool-label">Dimensions:</div>
        <pre class="tool-code">{{ input.width }} × {{ input.height }}</pre>
      </div>

      <div v-if="input.media" class="tool-section">
        <div class="tool-label">Media:</div>
        <pre class="tool-code">{{ input.media }}</pre>
      </div>

      <div v-if="isComplete && output" class="tool-section">
        <div class="tool-label">
          Output{{ hasError ? " (Error)" : "" }}:
          <span v-if="executionTime" class="tool-time">{{ executionTime }}</span>
        </div>
        <pre :class="`tool-code ${hasError ? 'error' : ''}`">{{ output }}</pre>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref } from "vue";
import type { LLMContent } from "../../../types";
import ToolChevron from "./ToolChevron.vue";
import RunningToolTime from "./RunningToolTime.vue";

interface EmulateInput {
  action?: string;
  device?: string;
  width?: number;
  height?: number;
  mobile?: boolean;
  touch?: boolean;
  device_scale_factor?: number;
  enabled?: boolean;
  media?: string;
}

const props = defineProps<{
  toolInput?: unknown;
  isRunning?: boolean;
  toolInvokedAt?: string | null;
  toolResult?: LLMContent[];
  hasError?: boolean;
  executionTime?: string;
}>();

const isExpanded = ref(false);

const input = computed<EmulateInput>(() =>
  typeof props.toolInput === "object" && props.toolInput !== null
    ? (props.toolInput as EmulateInput)
    : {},
);

const action = computed(() => input.value.action || "");
const device = computed(() => input.value.device || "");

const output = computed(() =>
  props.toolResult && props.toolResult.length > 0 && props.toolResult[0].Text
    ? props.toolResult[0].Text
    : "",
);

const isComplete = computed(() => !props.isRunning && props.toolResult !== undefined);

const summary = computed(() => {
  const i = input.value;
  const summaryParts: string[] = [action.value];
  if (device.value) summaryParts.push(device.value);
  if (i.width && i.height) summaryParts.push(`${i.width}×${i.height}`);
  if (i.media) summaryParts.push(i.media);
  if (i.enabled !== undefined) summaryParts.push(i.enabled ? "on" : "off");
  return summaryParts.filter(Boolean).join(" ") || "emulate";
});
</script>
