// ui/src/components/ThinkingContent.tsx
import React, { useState } from "react";
import { ChevronRightIcon } from "lucide-react";
import { cn } from "@/lib/utils";

interface ThinkingContentProps {
  thinking: string;
}

function ThinkingContent({ thinking }: ThinkingContentProps) {
  const [isExpanded, setIsExpanded] = useState(true);

  // Truncate thinking for display - get first 80 chars
  const truncateThinking = (text: string, maxLen: number = 80) => {
    if (!text) return "";
    const firstLine = text.split("\n")[0];
    if (firstLine.length <= maxLen) return firstLine;
    return firstLine.substring(0, maxLen) + "...";
  };

  const preview = truncateThinking(thinking);

  return (
    <div
      className="thinking-content my-1 rounded-lg border border-border bg-muted/40 text-sm"
      data-testid="thinking-content"
    >
      <div
        onClick={() => setIsExpanded(!isExpanded)}
        className="flex cursor-pointer items-start gap-2 px-3 py-2 select-none"
      >
        <span className="shrink-0 leading-none" aria-hidden>
          💭
        </span>
        <div
          className={cn(
            "min-w-0 flex-1 text-muted-foreground italic",
            isExpanded ? "whitespace-pre-wrap" : "truncate"
          )}
        >
          {isExpanded ? thinking : preview}
        </div>
        <button
          className="shrink-0 text-muted-foreground"
          aria-label={isExpanded ? "Collapse" : "Expand"}
          aria-expanded={isExpanded}
        >
          <ChevronRightIcon
            className={cn("size-3.5 transition-transform", isExpanded && "rotate-90")}
          />
        </button>
      </div>
    </div>
  );
}

export default ThinkingContent;

// ui/src/vue/components/tools/ThinkingContent.vue
<!-- Vue port of components/ThinkingContent.tsx. Collapsible chain-of-thought,
     default expanded. Preserves: .thinking-content, .thinking-content-wrapper,
     data-testid thinking-content, .thinking-clickable-area, .thinking-emoji 💭,
     .thinking-text, .thinking-toggle, .thinking-toggle-button. -->
<template>
  <div class="thinking-content thinking-content-wrapper" data-testid="thinking-content">
    <div class="thinking-clickable-area" @click="isExpanded = !isExpanded">
      <span class="thinking-emoji">💭</span>
      <div class="thinking-text">{{ isExpanded ? thinking : preview }}</div>
      <button
        class="thinking-toggle thinking-toggle-button"
        :aria-label="isExpanded ? 'Collapse' : 'Expand'"
        :aria-expanded="isExpanded"
      >
        <svg
          width="12"
          height="12"
          viewBox="0 0 12 12"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
          class="tool-chevron"
          :class="{ 'tool-chevron-expanded': isExpanded }"
        >
          <path
            d="M4.5 3L7.5 6L4.5 9"
            stroke="currentColor"
            stroke-width="1.5"
            stroke-linecap="round"
            stroke-linejoin="round"
          />
        </svg>
      </button>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref } from "vue";

const props = defineProps<{ thinking: string }>();

const isExpanded = ref(true);

// Truncate thinking for display - get first 80 chars
const truncateThinking = (text: string, maxLen = 80) => {
  if (!text) return "";
  const firstLine = text.split("\n")[0];
  if (firstLine.length <= maxLen) return firstLine;
  return firstLine.substring(0, maxLen) + "...";
};

const preview = computed(() => truncateThinking(props.thinking));
</script>
