// ui/src/vue/components/tools/BashTool.vue
<!-- Vue port of components/BashTool.tsx. Preserves the exact DOM classes and
     data-testid contract the e2e tests rely on (.bash-tool,
     .bash-tool-command, .bash-tool-code, .bash-tool-details,
     .bash-tool-header, tool-call-running/completed). -->
<template>
  <div class="bash-tool" :data-testid="isComplete ? 'tool-call-completed' : 'tool-call-running'">
    <div class="bash-tool-header" @click="isExpanded = !isExpanded">
      <div class="bash-tool-summary">
        <span class="bash-tool-emoji" :class="{ running: isRunning }">🛠️</span>
        <HighlightedCode
          class="bash-tool-command"
          :source="displayCommand"
          language="shellscript"
          :title="command"
        />
        <span v-if="summaryTruncated" class="bash-tool-summary-ellipsis">...</span>
        <span v-if="displayData?.workingDir" class="bash-tool-cwd ellipsis-start" :title="displayData.workingDir">
          in {{ displayData.workingDir }}
        </span>
      </div>
      <button
        class="bash-tool-toggle"
        :aria-label="isExpanded ? 'Collapse' : 'Expand'"
        :aria-expanded="isExpanded"
      >
        <ToolChevron :expanded="isExpanded" />
      </button>
    </div>

    <!-- Streaming preview — shown below header while running, outside details. -->
    <div v-if="isRunning && streamingOutput && !isExpanded" class="bash-tool-preview">
      <AnsiText ref="previewRef" class-name="bash-tool-preview-code" :text="visibleStreaming" />
      <button
        v-if="hasMoreLines && !previewExpanded"
        class="bash-tool-preview-more"
        @click.stop="previewExpanded = true"
      >
        Show all {{ lineCount }} lines
      </button>
    </div>

    <div v-if="isExpanded" class="bash-tool-details">
      <RunningToolTime v-if="isRunning" :start-time="toolInvokedAt" />
      <div v-if="displayData?.workingDir" class="bash-tool-section">
        <div class="bash-tool-label">Working Directory:</div>
        <pre class="bash-tool-code bash-tool-code-cwd">{{ displayData.workingDir }}</pre>
      </div>
      <div class="bash-tool-section">
        <div class="bash-tool-label">Command:</div>
        <HighlightedCode
          tag="pre"
          class="bash-tool-code"
          :source="command"
          language="shellscript"
        />
      </div>

      <div v-if="isRunning && streamingOutput" class="bash-tool-section">
        <div class="bash-tool-label">Output (streaming):</div>
        <AnsiText
          ref="expandedStreamRef"
          class-name="bash-tool-code bash-tool-streaming"
          :text="streamingOutput"
        />
      </div>

      <div v-if="isComplete" class="bash-tool-section">
        <div class="bash-tool-label">
          {{ outputLabel }}:
          <span v-if="executionTime" class="bash-tool-time">{{ executionTime }}</span>
        </div>
        <AnsiText
          :class-name="`bash-tool-code ${hasError ? 'error' : ''}`"
          :text="output || '(no output)'"
        />
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, nextTick, ref, watch } from "vue";
import type { LLMContent } from "../../../types";
import HighlightedCode from "../HighlightedCode.vue";
import AnsiText from "./AnsiText.vue";
import ToolChevron from "./ToolChevron.vue";
import RunningToolTime from "./RunningToolTime.vue";
import { isCancelledToolResult } from "../../utils/toolStatus";

interface BashDisplayData {
  workingDir: string;
  exitCode?: number;
}

const props = defineProps<{
  toolInput?: unknown;
  isRunning?: boolean;
  toolInvokedAt?: string | null;
  toolResult?: LLMContent[];
  hasError?: boolean;
  executionTime?: string;
  display?: unknown;
  streamingOutput?: string;
}>();

/** Max lines shown in the streaming preview before "Show more" is needed. */
const PREVIEW_LINES = 5;

// Details panel — collapsed by default.
const isExpanded = ref(false);
// Streaming preview — expanded to show full streaming output.
const previewExpanded = ref(false);
const previewRef = ref<InstanceType<typeof AnsiText> | null>(null);
const expandedStreamRef = ref<InstanceType<typeof AnsiText> | null>(null);

// Collapse details when the tool completes.
watch(
  () => props.isRunning,
  (running, prevRunning) => {
    if (prevRunning && !running) {
      isExpanded.value = false;
      previewExpanded.value = false;
    }
  },
);

// Auto-scroll streaming output to bottom (whichever ref is active).
watch(
  () => props.streamingOutput,
  async (out) => {
    if (!out) return;
    await nextTick();
    const el = previewRef.value?.preEl ?? expandedStreamRef.value?.preEl;
    if (el) el.scrollTop = el.scrollHeight;
  },
);

const displayData = computed<BashDisplayData | null>(() => {
  const d = props.display;
  if (
    d &&
    typeof d === "object" &&
    "workingDir" in d &&
    typeof (d as BashDisplayData).workingDir === "string"
  ) {
    return d as BashDisplayData;
  }
  return null;
});

const command = computed(() => {
  const ti = props.toolInput;
  if (
    typeof ti === "object" &&
    ti !== null &&
    "command" in ti &&
    typeof (ti as { command: unknown }).command === "string"
  ) {
    return (ti as { command: string }).command;
  }
  return typeof ti === "string" ? ti : "";
});

const output = computed(() =>
  props.toolResult && props.toolResult.length > 0 && props.toolResult[0].Text
    ? props.toolResult[0].Text
    : "",
);

const isCancelled = computed(() => props.hasError && isCancelledToolResult(output.value));

const outputLabel = computed(() => {
  if (isCancelled.value) return "Output (cancelled)";
  const exitCode = displayData.value?.exitCode;
  if (typeof exitCode === "number") return `Output (exit code ${exitCode})`;
  return props.hasError ? "Output (Error)" : "Output";
});

const displayCommand = computed(() => {
  const cmd = command.value;
  const maxLen = 300;
  return cmd.length <= maxLen ? cmd : cmd.substring(0, maxLen) + "...";
});

const isComplete = computed(() => !props.isRunning && props.toolResult !== undefined);

const visibleStreaming = computed(() => {
  if (!props.streamingOutput) return "";
  const lines = props.streamingOutput.split("\n");
  return previewExpanded.value ? props.streamingOutput : lines.slice(-PREVIEW_LINES).join("\n");
});
const hasMoreLines = computed(
  () => !!props.streamingOutput && props.streamingOutput.split("\n").length > PREVIEW_LINES,
);
const lineCount = computed(() =>
  props.streamingOutput ? props.streamingOutput.split("\n").length : 0,
);
</script>

// ui/src/components/BashTool.tsx
import React, { useMemo, useState } from "react";
import { LLMContent } from "../types";
import AnsiText from "./AnsiText";

// Display data from the bash tool backend
interface BashDisplayData {
  workingDir: string;
}

interface BashToolProps {
  // For tool_use (pending state)
  toolInput?: unknown;
  isRunning?: boolean;

  // For tool_result (completed state)
  toolResult?: LLMContent[];
  hasError?: boolean;
  executionTime?: string;
  display?: unknown;

  // Streaming output from tool progress
  streamingOutput?: string;
  streamingLineCount?: number;
}

/** Max lines shown in the streaming preview before "Show more" is needed. */
const PREVIEW_LINES = 5;

function logicalLines(text: string): string[] {
  const lines = text.split("\n");
  if (lines[lines.length - 1] === "") {
    lines.pop();
  }
  return lines;
}

function BashTool({
  toolInput,
  isRunning,
  toolResult,
  hasError,
  executionTime,
  display,
  streamingOutput,
  streamingLineCount,
}: BashToolProps) {
  // Details panel (command, full output) — collapsed by default, stays collapsed after completion.
  const [isExpanded, setIsExpanded] = useState(false);
  // Streaming preview — expanded to show full streaming output (beyond PREVIEW_LINES).
  const [previewExpanded, setPreviewExpanded] = useState(false);
  const previewRef = React.useRef<HTMLPreElement>(null);
  const expandedStreamRef = React.useRef<HTMLPreElement>(null);

  // Collapse details when tool completes (if we auto-expanded for streaming,
  // the user sees the preview instead, so the details panel should close).
  const prevRunning = React.useRef(isRunning);
  React.useEffect(() => {
    if (prevRunning.current && !isRunning) {
      setIsExpanded(false);
      setPreviewExpanded(false);
    }
    prevRunning.current = isRunning;
  }, [isRunning]);

  // Auto-scroll streaming output to bottom (whichever ref is active).
  React.useEffect(() => {
    const el = previewRef.current ?? expandedStreamRef.current;
    if (el && streamingOutput) {
      el.scrollTop = el.scrollHeight;
    }
  }, [streamingOutput]);

  // Extract working directory from display data
  const displayData: BashDisplayData | null =
    display &&
    typeof display === "object" &&
    "workingDir" in display &&
    typeof display.workingDir === "string"
      ? (display as BashDisplayData)
      : null;

  // Extract command from toolInput
  const command =
    typeof toolInput === "object" &&
    toolInput !== null &&
    "command" in toolInput &&
    typeof toolInput.command === "string"
      ? toolInput.command
      : typeof toolInput === "string"
        ? toolInput
        : "";

  // Extract output from toolResult
  const output =
    toolResult && toolResult.length > 0 && toolResult[0].Text ? toolResult[0].Text : "";

  // Check if this was a cancelled operation
  const isCancelled = hasError && output.toLowerCase().includes("cancel");

  // Truncate command for display
  const truncateCommand = (cmd: string, maxLen: number = 300) => {
    if (cmd.length <= maxLen) return cmd;
    return cmd.substring(0, maxLen) + "...";
  };

  const displayCommand = truncateCommand(command);
  const isComplete = !isRunning && toolResult !== undefined;

  // Compute streaming preview: show last N lines by default.
  const { visibleStreaming, hasMoreLines, lineCount } = useMemo(() => {
    if (!streamingOutput) return { visibleStreaming: "", hasMoreLines: false, lineCount: 0 };
    const lines = logicalLines(streamingOutput);
    const lineCount = streamingLineCount ?? lines.length;
    return {
      visibleStreaming: previewExpanded ? streamingOutput : lines.slice(-PREVIEW_LINES).join("\n"),
      hasMoreLines: lineCount > PREVIEW_LINES,
      lineCount,
    };
  }, [streamingOutput, streamingLineCount, previewExpanded]);

  return (
    <div
      className="bash-tool"
      data-testid={isComplete ? "tool-call-completed" : "tool-call-running"}
    >
      <div className="bash-tool-header" onClick={() => setIsExpanded(!isExpanded)}>
        <div className="bash-tool-summary">
          <span className={`bash-tool-emoji ${isRunning ? "running" : ""}`}>🛠️</span>
          <span className="bash-tool-command" title={command}>
            {displayCommand}
          </span>
          {displayData?.workingDir && (
            <span className="bash-tool-cwd" title={displayData.workingDir}>
              in {displayData.workingDir}
            </span>
          )}
          {isComplete && isCancelled && <span className="bash-tool-cancelled">✗ cancelled</span>}
          {isComplete && hasError && !isCancelled && <span className="bash-tool-error">✗</span>}
          {isComplete && !hasError && <span className="bash-tool-success">✓</span>}
        </div>
        <button
          className="bash-tool-toggle"
          aria-label={isExpanded ? "Collapse" : "Expand"}
          aria-expanded={isExpanded}
        >
          <svg
            width="12"
            height="12"
            viewBox="0 0 12 12"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
            className={`tool-chevron${isExpanded ? " tool-chevron-expanded" : ""}`}
          >
            <path
              d="M4.5 3L7.5 6L4.5 9"
              stroke="currentColor"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
            />
          </svg>
        </button>
      </div>

      {/* Streaming preview — shown below header while running, outside the details panel */}
      {isRunning && streamingOutput && !isExpanded && (
        <div className="bash-tool-preview">
          <AnsiText ref={previewRef} className="bash-tool-preview-code" text={visibleStreaming} />
          {hasMoreLines && !previewExpanded && (
            <button
              className="bash-tool-preview-more"
              onClick={(e) => {
                e.stopPropagation();
                setPreviewExpanded(true);
              }}
            >
              Show all {lineCount} lines
            </button>
          )}
        </div>
      )}

      {isExpanded && (
        <div className="bash-tool-details">
          {displayData?.workingDir && (
            <div className="bash-tool-section">
              <div className="bash-tool-label">Working Directory:</div>
              <pre className="bash-tool-code bash-tool-code-cwd">{displayData.workingDir}</pre>
            </div>
          )}
          <div className="bash-tool-section">
            <div className="bash-tool-label">Command:</div>
            <pre className="bash-tool-code">{command}</pre>
          </div>

          {isRunning && streamingOutput && (
            <div className="bash-tool-section">
              <div className="bash-tool-label">Output (streaming):</div>
              <AnsiText
                ref={expandedStreamRef}
                className="bash-tool-code bash-tool-streaming"
                text={streamingOutput}
              />
            </div>
          )}

          {isComplete && (
            <div className="bash-tool-section">
              <div className="bash-tool-label">
                Output{hasError ? " (Error)" : ""}:
                {executionTime && <span className="bash-tool-time">{executionTime}</span>}
              </div>
              <AnsiText
                className={`bash-tool-code ${hasError ? "error" : ""}`}
                text={output || "(no output)"}
              />
            </div>
          )}
        </div>
      )}
    </div>
  );
}

export default BashTool;
