// ui/src/vue/components/tools/BrowserAccessibilityTool.vue
<!-- Vue port of components/BrowserAccessibilityTool.tsx. Preserves the exact
     DOM classes, data-testid, and aria contracts the e2e tests rely on. -->
<template>
  <div class="tool" :data-testid="isComplete ? 'tool-call-completed' : 'tool-call-running'">
    <div class="tool-header" @click="isExpanded = !isExpanded">
      <div class="tool-summary">
        <span class="tool-emoji" :class="{ running: isRunning }">🌳</span>
        <span class="tool-command ellipsis-start">{{ summary }}</span>
      </div>
      <button
        class="tool-toggle"
        :aria-label="isExpanded ? 'Collapse' : 'Expand'"
        :aria-expanded="isExpanded"
      >
        <ToolChevron :expanded="isExpanded" />
      </button>
    </div>

    <div v-if="isExpanded" class="tool-details">
      <RunningToolTime v-if="isRunning" :start-time="toolInvokedAt" />
      <div class="tool-section">
        <div class="tool-label">Action:</div>
        <pre class="tool-code">{{ action || "(none)" }}</pre>
      </div>

      <div v-if="input.name" class="tool-section">
        <div class="tool-label">Name:</div>
        <pre class="tool-code">{{ input.name }}</pre>
      </div>

      <div v-if="input.role" class="tool-section">
        <div class="tool-label">Role:</div>
        <pre class="tool-code">{{ input.role }}</pre>
      </div>

      <div v-if="input.selector" class="tool-section">
        <div class="tool-label">Selector:</div>
        <pre class="tool-code">{{ input.selector }}</pre>
      </div>

      <div v-if="input.depth !== undefined" class="tool-section">
        <div class="tool-label">Depth:</div>
        <pre class="tool-code">{{ input.depth }}</pre>
      </div>

      <div v-if="isComplete && output" class="tool-section">
        <div class="tool-label">
          Output{{ hasError ? " (Error)" : "" }}:
          <span v-if="executionTime" class="tool-time">{{ executionTime }}</span>
        </div>
        <pre :class="`tool-code ${hasError ? 'error' : ''}`">{{ output }}</pre>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref } from "vue";
import type { LLMContent } from "../../../types";
import ToolChevron from "./ToolChevron.vue";
import RunningToolTime from "./RunningToolTime.vue";

interface AccessibilityInput {
  action?: string;
  depth?: number;
  name?: string;
  role?: string;
  selector?: string;
}

const props = defineProps<{
  toolInput?: unknown;
  isRunning?: boolean;
  toolInvokedAt?: string | null;
  toolResult?: LLMContent[];
  hasError?: boolean;
  executionTime?: string;
}>();

const isExpanded = ref(false);

const input = computed<AccessibilityInput>(() =>
  typeof props.toolInput === "object" && props.toolInput !== null
    ? (props.toolInput as AccessibilityInput)
    : {},
);

const action = computed(() => input.value.action || "");

const output = computed(() =>
  props.toolResult && props.toolResult.length > 0 && props.toolResult[0].Text
    ? props.toolResult[0].Text
    : "",
);

const isComplete = computed(() => !props.isRunning && props.toolResult !== undefined);

const summary = computed(() => {
  const i = input.value;
  const summaryParts: string[] = [action.value];
  if (i.name) summaryParts.push(`name="${i.name}"`);
  if (i.role) summaryParts.push(`role=${i.role}`);
  if (i.selector) summaryParts.push(i.selector);
  if (i.depth !== undefined) summaryParts.push(`depth=${i.depth}`);
  return summaryParts.filter(Boolean).join(" ") || "accessibility";
});
</script>

// ui/src/components/BrowserAccessibilityTool.tsx
import React from "react";
import { LLMContent } from "../types";
import { ToolCard, ToolSection, ToolCode, ToolStatusMark } from "./ToolCard";

interface BrowserAccessibilityToolProps {
  toolInput?: unknown;
  isRunning?: boolean;
  toolResult?: LLMContent[];
  hasError?: boolean;
  executionTime?: string;
}

function BrowserAccessibilityTool({
  toolInput,
  isRunning,
  toolResult,
  hasError,
  executionTime,
}: BrowserAccessibilityToolProps) {
  const input =
    typeof toolInput === "object" && toolInput !== null
      ? (toolInput as {
          action?: string;
          depth?: number;
          name?: string;
          role?: string;
          selector?: string;
        })
      : {};

  const action = input.action || "";

  const output =
    toolResult && toolResult.length > 0 && toolResult[0].Text ? toolResult[0].Text : "";

  const isComplete = !isRunning && toolResult !== undefined;

  // Build compact summary showing action and query params
  const summaryParts: string[] = [action];
  if (input.name) summaryParts.push(`name="${input.name}"`);
  if (input.role) summaryParts.push(`role=${input.role}`);
  if (input.selector) summaryParts.push(input.selector);
  if (input.depth !== undefined) summaryParts.push(`depth=${input.depth}`);
  const summary = summaryParts.filter(Boolean).join(" ") || "accessibility";

  return (
    <ToolCard
      emoji="♿"
      running={isRunning}
      complete={isComplete}
      title={summary}
      status={isComplete ? <ToolStatusMark error={hasError} /> : null}
    >
      <ToolSection label="Action:">
        <ToolCode>{action || "(none)"}</ToolCode>
      </ToolSection>

      {input.name && (
        <ToolSection label="Name:">
          <ToolCode>{input.name}</ToolCode>
        </ToolSection>
      )}

      {input.role && (
        <ToolSection label="Role:">
          <ToolCode>{input.role}</ToolCode>
        </ToolSection>
      )}

      {input.selector && (
        <ToolSection label="Selector:">
          <ToolCode>{input.selector}</ToolCode>
        </ToolSection>
      )}

      {input.depth !== undefined && (
        <ToolSection label="Depth:">
          <ToolCode>{input.depth}</ToolCode>
        </ToolSection>
      )}

      {isComplete && output && (
        <ToolSection
          label={
            <span className="flex items-center gap-2">
              <span>Output{hasError ? " (Error)" : ""}:</span>
              {executionTime && (
                <span className="text-muted-foreground">{executionTime}</span>
              )}
            </span>
          }
        >
          <ToolCode error={hasError}>{output}</ToolCode>
        </ToolSection>
      )}
    </ToolCard>
  );
}

export default BrowserAccessibilityTool;
