// ui/src/vue/components/tools/ChangeDirTool.vue
<!-- Vue port of components/ChangeDirTool.tsx.
     Preserves: .tool, .tool-header, .tool-summary, .tool-emoji, .tool-command,
     .tool-toggle, .tool-details, .tool-section, .tool-label, .tool-code,
     data-testid tool-call-running/completed. -->
<template>
  <div class="tool" :data-testid="isComplete ? 'tool-call-completed' : 'tool-call-running'">
    <div class="tool-header" @click="isExpanded = !isExpanded">
      <div class="tool-summary">
        <span class="tool-emoji" :class="{ running: isRunning }">📂</span>
        <span class="tool-command ellipsis-start">cd {{ path || "..." }}</span>
      </div>
      <button
        class="tool-toggle"
        :aria-label="isExpanded ? 'Collapse' : 'Expand'"
        :aria-expanded="isExpanded"
      >
        <ToolChevron :expanded="isExpanded" />
      </button>
    </div>

    <div v-if="isExpanded" class="tool-details">
      <RunningToolTime v-if="isRunning" :start-time="toolInvokedAt" />
      <div class="tool-section">
        <div class="tool-label">
          Path:
          <span v-if="executionTime" class="tool-time">{{ executionTime }}</span>
        </div>
        <div :class="`tool-code ${hasError ? 'error' : ''}`">{{ path || "(no path)" }}</div>
      </div>
      <div v-if="isComplete" class="tool-section">
        <div class="tool-label">Result{{ hasError ? " (Error)" : "" }}:</div>
        <div :class="`tool-code ${hasError ? 'error' : ''}`">{{ resultText || "(no output)" }}</div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref } from "vue";
import type { LLMContent } from "../../../types";
import ToolChevron from "./ToolChevron.vue";
import RunningToolTime from "./RunningToolTime.vue";

const props = defineProps<{
  toolInput?: unknown;
  isRunning?: boolean;
  toolInvokedAt?: string | null;
  toolResult?: LLMContent[];
  hasError?: boolean;
  executionTime?: string;
}>();

const isExpanded = ref(false);

const path = computed(() => {
  const ti = props.toolInput;
  if (
    typeof ti === "object" &&
    ti !== null &&
    "path" in ti &&
    typeof (ti as { path: unknown }).path === "string"
  ) {
    return (ti as { path: string }).path;
  }
  return "";
});

const resultText = computed(
  () =>
    props.toolResult
      ?.map((r) => r.Text)
      .filter(Boolean)
      .join("") || "",
);

const isComplete = computed(() => !props.isRunning && props.toolResult !== undefined);
</script>

// ui/src/components/ChangeDirTool.tsx
import React from "react";
import { LLMContent } from "../types";
import { ToolCard, ToolSection, ToolCode, ToolStatusMark } from "./ToolCard";

interface ChangeDirToolProps {
  // For tool_use (pending state)
  toolInput?: unknown; // { path: string }
  isRunning?: boolean;

  // For tool_result (completed state)
  toolResult?: LLMContent[];
  hasError?: boolean;
  executionTime?: string;
}

function ChangeDirTool({
  toolInput,
  isRunning,
  toolResult,
  hasError,
  executionTime,
}: ChangeDirToolProps) {
  // Extract path from toolInput
  const path =
    typeof toolInput === "object" &&
    toolInput !== null &&
    "path" in toolInput &&
    typeof (toolInput as { path: unknown }).path === "string"
      ? (toolInput as { path: string }).path
      : "";

  // Get result text
  const resultText =
    toolResult
      ?.map((r) => r.Text)
      .filter(Boolean)
      .join("") || "";

  const isComplete = !isRunning && toolResult !== undefined;

  return (
    <ToolCard
      emoji="📂"
      running={isRunning}
      complete={isComplete}
      title={`cd ${path || "..."}`}
      status={isComplete ? <ToolStatusMark error={hasError} /> : null}
    >
      <ToolSection
        label={
          <span className="flex items-center gap-2">
            <span>Path:</span>
            {executionTime && (
              <span className="text-muted-foreground">{executionTime}</span>
            )}
          </span>
        }
      >
        <ToolCode error={hasError}>{path || "(no path)"}</ToolCode>
      </ToolSection>
      {isComplete && (
        <ToolSection label="Result:">
          <ToolCode error={hasError}>{resultText || "(no output)"}</ToolCode>
        </ToolSection>
      )}
    </ToolCard>
  );
}

export default ChangeDirTool;
