// ui/src/vue/components/DirectoryPickerModal.vue
<!-- Vue port of components/DirectoryPickerModal.tsx. FS browse + cwd pick +
     inline mkdir. Preserves the directory-picker-* class contract, the
     modal-overlay/modal chrome with aria-label "Close modal", and the "New
     folder name" sr-only label. Uses api.listDirectory/createDirectory and
     escapeClose. Renders plain elements (no Modal.vue) to keep the custom
     footer + directory-picker-modal class. -->
<template>
  <div v-if="isOpen" class="modal-overlay" @click="onBackdrop">
    <div class="modal directory-picker-modal">
      <!-- Header -->
      <div class="modal-header">
        <h2 class="modal-title">Select Directory</h2>
        <button class="btn-icon" aria-label="Close modal" @click="emit('close')">
          <svg fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              :stroke-width="2"
              d="M6 18L18 6M6 6l12 12"
            />
          </svg>
        </button>
      </div>

      <!-- Content -->
      <div class="modal-body directory-picker-body">
        <div class="directory-picker-input-container">
          <input
            ref="inputRef"
            type="text"
            v-model="inputPath"
            class="directory-picker-input"
            placeholder="/path/to/directory"
            @keydown="handleInputKeyDown"
          />
        </div>

        <div
          v-if="displayDir"
          :class="`directory-picker-current${displayDir.git_head_subject ? ' directory-picker-current-git' : ''}`"
        >
          <span class="directory-picker-current-path">
            {{ displayDir.path }}
            <span v-if="filterPrefix" class="directory-picker-filter">/{{ filterPrefix }}*</span>
          </span>
          <span
            v-if="displayDir.git_head_subject"
            class="directory-picker-current-subject"
            :title="displayDir.git_head_subject"
          >
            {{ displayDir.git_head_subject }}
          </span>
        </div>

        <div
          v-if="displayDir && (displayDir.git_repo_root || displayDir.git_worktree_root)"
          class="directory-picker-git-root-row"
        >
          <button
            v-if="displayDir.git_repo_root && displayDir.git_repo_root !== displayDir.path"
            class="directory-picker-git-root-btn"
            :title="displayDir.git_repo_root"
            @click="inputPath = displayDir.git_repo_root + '/'"
          >
            <svg
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
              class="directory-picker-icon"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                :stroke-width="2"
                d="M3 10h10a8 8 0 018 8v2M3 10l6 6m-6-6l6-6"
              />
            </svg>
            <span>Go to git worktree root</span>
            <span class="directory-picker-git-root-path">{{ displayDir.git_repo_root }}</span>
          </button>
          <button
            v-if="displayDir.git_worktree_root && displayDir.git_worktree_root !== displayDir.path"
            class="directory-picker-git-root-btn"
            :title="displayDir.git_worktree_root"
            @click="inputPath = displayDir.git_worktree_root + '/'"
          >
            <svg
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
              class="directory-picker-icon"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                :stroke-width="2"
                d="M3 10h10a8 8 0 018 8v2M3 10l6 6m-6-6l6-6"
              />
            </svg>
            <span>Go to git root</span>
            <span class="directory-picker-git-root-path">{{ displayDir.git_worktree_root }}</span>
          </button>
        </div>

        <div v-if="error" class="directory-picker-error">{{ error }}</div>

        <div v-if="loading" class="directory-picker-loading">
          <div class="spinner spinner-small"></div>
          <span>Loading...</span>
        </div>

        <div v-if="!loading && !error" class="directory-picker-list">
          <button
            v-if="showParent"
            class="directory-picker-entry directory-picker-entry-parent"
            @click="handleParentClick"
          >
            <svg
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
              class="directory-picker-icon"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                :stroke-width="2"
                d="M11 17l-5-5m0 0l5-5m-5 5h12"
              />
            </svg>
            <span>..</span>
          </button>

          <button
            v-for="entry in filteredEntries"
            :key="entry.name"
            :class="`directory-picker-entry${entry.git_head_subject ? ' directory-picker-entry-git' : ''}`"
            @click="handleEntryClick(entry)"
          >
            <svg
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
              class="directory-picker-icon"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                :stroke-width="2"
                d="M3 7v10a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-6l-2-2H5a2 2 0 00-2 2z"
              />
            </svg>
            <span class="directory-picker-entry-name">
              <template
                v-if="
                  filterPrefix && entry.name.toLowerCase().startsWith(filterPrefix.toLowerCase())
                "
              >
                <strong>{{ entry.name.slice(0, filterPrefix.length) }}</strong
                >{{ entry.name.slice(filterPrefix.length) }}
              </template>
              <template v-else>{{ entry.name }}</template>
            </span>
            <span
              v-if="entry.git_head_subject"
              class="directory-picker-git-subject"
              :title="entry.git_head_subject"
            >
              {{ entry.git_head_subject }}
            </span>
          </button>

          <!-- Create new directory inline form -->
          <div v-if="isCreating" class="directory-picker-create-form">
            <svg
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
              class="directory-picker-icon"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                :stroke-width="2"
                d="M9 13h6m-3-3v6m-9 1V7a2 2 0 012-2h6l2 2h6a2 2 0 012 2v8a2 2 0 01-2 2H5a2 2 0 01-2-2z"
              />
            </svg>
            <label :for="createInputId" class="sr-only">New folder name</label>
            <input
              :id="createInputId"
              ref="newDirInputRef"
              type="text"
              v-model="newDirName"
              placeholder="New folder name"
              class="directory-picker-create-input"
              :disabled="createLoading"
              @keydown="handleCreateKeyDown"
            />
            <button
              class="directory-picker-create-btn"
              :disabled="createLoading || !newDirName.trim()"
              title="Create"
              @click="handleCreateDirectory"
            >
              <div v-if="createLoading" class="spinner spinner-small"></div>
              <svg v-else fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  :stroke-width="2"
                  d="M5 13l4 4L19 7"
                />
              </svg>
            </button>
            <button
              class="directory-picker-create-btn directory-picker-cancel-btn"
              :disabled="createLoading"
              title="Cancel"
              @click="handleCancelCreate"
            >
              <svg fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  :stroke-width="2"
                  d="M6 18L18 6M6 6l12 12"
                />
              </svg>
            </button>
          </div>

          <div v-if="createError" class="directory-picker-create-error">{{ createError }}</div>

          <div
            v-if="filteredEntries.length === 0 && !showParent && !isCreating"
            class="directory-picker-empty"
          >
            {{ filterPrefix ? "No matching directories" : "No subdirectories" }}
          </div>
        </div>
      </div>

      <!-- Footer -->
      <div class="directory-picker-footer">
        <button
          v-if="!isCreating && !loading && !error"
          class="btn directory-picker-new-btn"
          title="Create new folder"
          @click="handleStartCreate"
        >
          <svg
            fill="none"
            stroke="currentColor"
            viewBox="0 0 24 24"
            class="directory-picker-new-icon"
          >
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              :stroke-width="2"
              d="M9 13h6m-3-3v6m-9 1V7a2 2 0 012-2h6l2 2h6a2 2 0 012 2v8a2 2 0 01-2 2H5a2 2 0 01-2-2z"
            />
          </svg>
          New Folder
        </button>
        <div class="directory-picker-footer-spacer"></div>
        <button class="btn" @click="emit('close')">Cancel</button>
        <button class="btn-primary" :disabled="loading || !!error" @click="handleSelect">
          Select
        </button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, nextTick, ref, watch } from "vue";
import { api } from "../../services/api";
import { useEscapeClose } from "../composables/escapeClose";

interface DirectoryEntry {
  name: string;
  is_dir: boolean;
  git_head_subject?: string;
}

interface CachedDirectory {
  path: string;
  parent: string;
  entries: DirectoryEntry[];
  git_head_subject?: string;
  git_repo_root?: string;
  git_worktree_root?: string;
}

const props = defineProps<{
  isOpen: boolean;
  initialPath?: string;
  foldersOnly?: boolean;
}>();
const emit = defineEmits<{ (e: "close"): void; (e: "select", path: string): void }>();

let createIdCounter = 0;
const createInputId = `dirpicker-create-${++createIdCounter}`;

const inputPath = ref(
  props.initialPath
    ? props.initialPath.endsWith("/")
      ? props.initialPath
      : props.initialPath + "/"
    : "",
);
const loading = ref(false);
const error = ref<string | null>(null);
const inputRef = ref<HTMLInputElement | null>(null);

const isCreating = ref(false);
const newDirName = ref("");
const createError = ref<string | null>(null);
const createLoading = ref(false);
const newDirInputRef = ref<HTMLInputElement | null>(null);

const cache = new Map<string, CachedDirectory>();

const displayDir = ref<CachedDirectory | null>(null);
const filterPrefix = ref("");
let expectedPath = "";

function parseInputPath(path: string): { dirPath: string; prefix: string } {
  if (!path) return { dirPath: "", prefix: "" };
  if (path.endsWith("/")) return { dirPath: path.slice(0, -1) || "/", prefix: "" };
  const lastSlash = path.lastIndexOf("/");
  if (lastSlash === -1) return { dirPath: "", prefix: path };
  if (lastSlash === 0) return { dirPath: "/", prefix: path.slice(1) };
  return { dirPath: path.slice(0, lastSlash), prefix: path.slice(lastSlash + 1) };
}

async function loadDirectory(path: string): Promise<CachedDirectory | null> {
  const normalizedPath = path || "/";
  const cached = cache.get(normalizedPath);
  if (cached) return cached;

  loading.value = true;
  error.value = null;
  try {
    const result = await api.listDirectory(path || undefined);
    if (result.error) {
      error.value = result.error;
      return null;
    }
    const dirData: CachedDirectory = {
      path: result.path,
      parent: result.parent,
      entries: result.entries || [],
      git_head_subject: result.git_head_subject,
      git_repo_root: result.git_repo_root,
      git_worktree_root: result.git_worktree_root,
    };
    cache.set(result.path, dirData);
    return dirData;
  } catch (err) {
    error.value = err instanceof Error ? err.message : "Failed to load directory";
    return null;
  } finally {
    loading.value = false;
  }
}

const filteredEntries = computed(
  () =>
    displayDir.value?.entries.filter((entry) => {
      if (props.foldersOnly && !entry.is_dir) return false;
      if (!filterPrefix.value) return true;
      return entry.name.toLowerCase().startsWith(filterPrefix.value.toLowerCase());
    }) || [],
);

const showParent = computed(() => !!displayDir.value?.parent && displayDir.value.parent !== "");

function handleEntryClick(entry: DirectoryEntry) {
  if (entry.is_dir) {
    const basePath = displayDir.value?.path || "";
    inputPath.value = basePath === "/" ? `/${entry.name}/` : `${basePath}/${entry.name}/`;
  }
}

function handleParentClick() {
  if (displayDir.value?.parent) {
    inputPath.value = displayDir.value.parent === "/" ? "/" : `${displayDir.value.parent}/`;
  }
}

function handleInputKeyDown(e: KeyboardEvent) {
  if (e.isComposing) return;
  if (e.key === "Enter") {
    e.preventDefault();
    handleSelect();
  }
}

function handleSelect() {
  const { dirPath } = parseInputPath(inputPath.value);
  const selectedPath = inputPath.value.endsWith("/") ? (dirPath === "/" ? "/" : dirPath) : dirPath;
  emit("select", selectedPath || displayDir.value?.path || "");
  emit("close");
}

function handleStartCreate() {
  isCreating.value = true;
  newDirName.value = "";
  createError.value = null;
}

function handleCancelCreate() {
  isCreating.value = false;
  newDirName.value = "";
  createError.value = null;
}

async function handleCreateDirectory() {
  if (!newDirName.value.trim()) {
    createError.value = "Directory name is required";
    return;
  }
  if (newDirName.value.includes("/") || newDirName.value.includes("\\")) {
    createError.value = "Directory name cannot contain slashes";
    return;
  }
  const basePath = displayDir.value?.path || "/";
  const newPath = basePath === "/" ? `/${newDirName.value}` : `${basePath}/${newDirName.value}`;

  createLoading.value = true;
  createError.value = null;
  try {
    const result = await api.createDirectory(newPath);
    if (result.error) {
      createError.value = result.error;
      return;
    }
    cache.delete(basePath);
    isCreating.value = false;
    newDirName.value = "";
    inputPath.value = newPath + "/";
  } catch (err) {
    createError.value = err instanceof Error ? err.message : "Failed to create directory";
  } finally {
    createLoading.value = false;
  }
}

function handleCreateKeyDown(e: KeyboardEvent) {
  if (e.isComposing) return;
  if (e.key === "Enter") {
    e.preventDefault();
    handleCreateDirectory();
  } else if (e.key === "Escape") {
    e.preventDefault();
    handleCancelCreate();
  }
}

function onBackdrop(e: MouseEvent) {
  if (e.target === e.currentTarget) emit("close");
}

useEscapeClose(
  () => props.isOpen,
  () => emit("close"),
);

// Update display when input changes (while open).
watch(
  [() => props.isOpen, inputPath],
  ([open]) => {
    if (!open) return;
    const { dirPath, prefix } = parseInputPath(inputPath.value);
    filterPrefix.value = prefix;
    const normalizedDirPath = dirPath || "/";
    expectedPath = normalizedDirPath;
    loadDirectory(dirPath).then((dir) => {
      if (dir && expectedPath === normalizedDirPath) {
        displayDir.value = dir;
        error.value = null;
      }
    });
  },
  { immediate: true },
);

// Initialize + focus when modal opens.
watch(
  () => props.isOpen,
  (open) => {
    if (open) {
      if (!props.initialPath) {
        inputPath.value = "";
      } else {
        inputPath.value = props.initialPath.endsWith("/")
          ? props.initialPath
          : props.initialPath + "/";
      }
      cache.clear();
      nextTick(() => {
        const el = inputRef.value;
        if (!el) return;
        const isMobile =
          window.matchMedia("(max-width: 768px)").matches || "ontouchstart" in window;
        if (!isMobile) {
          el.focus();
          const len = el.value.length;
          el.setSelectionRange(len, len);
        }
      });
    }
  },
);

// Focus the new-directory input when entering create mode.
watch(isCreating, (creating) => {
  if (creating) nextTick(() => newDirInputRef.value?.focus());
});
</script>

// ui/src/components/DirectoryPickerModal.tsx
import React, { useState, useEffect, useRef, useCallback, useId } from "react";
import {
  CheckIcon,
  CornerLeftUpIcon,
  FolderIcon,
  FolderPlusIcon,
  GitBranchIcon,
  Loader2Icon,
  XIcon,
} from "lucide-react";
import { api } from "../services/api";
import Modal from "./Modal";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { cn } from "@/lib/utils";

interface DirectoryEntry {
  name: string;
  is_dir: boolean;
  git_head_subject?: string;
}

interface CachedDirectory {
  path: string;
  parent: string;
  entries: DirectoryEntry[];
  git_head_subject?: string;
  git_repo_root?: string;
  git_worktree_root?: string;
}

interface DirectoryPickerModalProps {
  isOpen: boolean;
  onClose: () => void;
  onSelect: (path: string) => void;
  initialPath?: string;
  foldersOnly?: boolean; // If true, only show directories (hide files)
}

function DirectoryPickerModal({
  isOpen,
  onClose,
  onSelect,
  initialPath,
  foldersOnly,
}: DirectoryPickerModalProps) {
  const [inputPath, setInputPath] = useState(() => {
    if (!initialPath) return "";
    return initialPath.endsWith("/") ? initialPath : initialPath + "/";
  });
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const inputRef = useRef<HTMLInputElement>(null);

  // State for create directory mode
  const [isCreating, setIsCreating] = useState(false);
  const [newDirName, setNewDirName] = useState("");
  const [createError, setCreateError] = useState<string | null>(null);
  const [createLoading, setCreateLoading] = useState(false);
  const newDirInputRef = useRef<HTMLInputElement>(null);
  const createInputId = useId();

  // Cache for directory listings
  const cacheRef = useRef<Map<string, CachedDirectory>>(new Map());

  // Current directory being displayed (the parent directory of what's being typed)
  const [displayDir, setDisplayDir] = useState<CachedDirectory | null>(null);
  // Filter prefix (the part after the last slash that we're filtering by)
  const [filterPrefix, setFilterPrefix] = useState("");

  // Parse input path into directory and filter prefix
  const parseInputPath = useCallback((path: string): { dirPath: string; prefix: string } => {
    if (!path) {
      return { dirPath: "", prefix: "" };
    }

    // If path ends with /, we're looking at contents of that directory
    if (path.endsWith("/")) {
      return { dirPath: path.slice(0, -1) || "/", prefix: "" };
    }

    // Otherwise, split into directory and prefix
    const lastSlash = path.lastIndexOf("/");
    if (lastSlash === -1) {
      // No slash, treat as prefix in current directory
      return { dirPath: "", prefix: path };
    }
    if (lastSlash === 0) {
      // Root directory with prefix
      return { dirPath: "/", prefix: path.slice(1) };
    }
    return {
      dirPath: path.slice(0, lastSlash),
      prefix: path.slice(lastSlash + 1),
    };
  }, []);

  // Load directory from cache or API
  const loadDirectory = useCallback(async (path: string): Promise<CachedDirectory | null> => {
    const normalizedPath = path || "/";

    // Check cache first
    const cached = cacheRef.current.get(normalizedPath);
    if (cached) {
      return cached;
    }

    // Load from API
    setLoading(true);
    setError(null);
    try {
      const result = await api.listDirectory(path || undefined);
      if (result.error) {
        setError(result.error);
        return null;
      }

      const dirData: CachedDirectory = {
        path: result.path,
        parent: result.parent,
        entries: result.entries || [],
        git_head_subject: result.git_head_subject,
        git_repo_root: result.git_repo_root,
        git_worktree_root: result.git_worktree_root,
      };

      // Cache it
      cacheRef.current.set(result.path, dirData);

      return dirData;
    } catch (err) {
      setError(err instanceof Error ? err.message : "Failed to load directory");
      return null;
    } finally {
      setLoading(false);
    }
  }, []);

  // Track the current expected path to avoid race conditions
  const expectedPathRef = useRef<string>("");

  // Update display when input changes
  useEffect(() => {
    if (!isOpen) return;

    const { dirPath, prefix } = parseInputPath(inputPath);
    setFilterPrefix(prefix);

    // Track which path we expect to display
    const normalizedDirPath = dirPath || "/";
    expectedPathRef.current = normalizedDirPath;

    // Load the directory
    loadDirectory(dirPath).then((dir) => {
      // Only update if this is still the path we want
      if (dir && expectedPathRef.current === normalizedDirPath) {
        setDisplayDir(dir);
        setError(null);
      }
    });
  }, [isOpen, inputPath, parseInputPath, loadDirectory]);

  // Initialize when modal opens
  useEffect(() => {
    if (isOpen) {
      if (!initialPath) {
        setInputPath("");
      } else {
        setInputPath(initialPath.endsWith("/") ? initialPath : initialPath + "/");
      }
      // Clear cache on open to get fresh data
      cacheRef.current.clear();
    }
  }, [isOpen, initialPath]);

  // Focus input when modal opens (but not on mobile to avoid keyboard popup)
  useEffect(() => {
    if (isOpen && inputRef.current) {
      // Check if mobile device (touch-based)
      const isMobile = window.matchMedia("(max-width: 768px)").matches || "ontouchstart" in window;
      if (!isMobile) {
        inputRef.current.focus();
        // Move cursor to end
        const len = inputRef.current.value.length;
        inputRef.current.setSelectionRange(len, len);
      }
    }
  }, [isOpen]);

  // Filter entries based on prefix (case-insensitive)
  const filteredEntries =
    displayDir?.entries.filter((entry) => {
      if (foldersOnly && !entry.is_dir) return false;
      if (!filterPrefix) return true;
      return entry.name.toLowerCase().startsWith(filterPrefix.toLowerCase());
    }) || [];

  const handleEntryClick = (entry: DirectoryEntry) => {
    if (entry.is_dir) {
      const basePath = displayDir?.path || "";
      const newPath = basePath === "/" ? `/${entry.name}/` : `${basePath}/${entry.name}/`;
      setInputPath(newPath);
    }
  };

  const handleParentClick = () => {
    if (displayDir?.parent) {
      const newPath = displayDir.parent === "/" ? "/" : `${displayDir.parent}/`;
      setInputPath(newPath);
    }
  };

  const handleInputKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    // Don't submit while IME is composing (e.g., converting Japanese hiragana to kanji)
    if (e.nativeEvent.isComposing) {
      return;
    }
    if (e.key === "Enter") {
      e.preventDefault();
      handleSelect();
    }
  };

  const handleSelect = () => {
    // Use the current directory path for selection
    const { dirPath } = parseInputPath(inputPath);
    const selectedPath = inputPath.endsWith("/") ? (dirPath === "/" ? "/" : dirPath) : dirPath;
    onSelect(selectedPath || displayDir?.path || "");
    onClose();
  };

  // Focus the new directory input when entering create mode
  useEffect(() => {
    if (isCreating && newDirInputRef.current) {
      newDirInputRef.current.focus();
    }
  }, [isCreating]);

  const handleStartCreate = () => {
    setIsCreating(true);
    setNewDirName("");
    setCreateError(null);
  };

  const handleCancelCreate = () => {
    setIsCreating(false);
    setNewDirName("");
    setCreateError(null);
  };

  const handleCreateDirectory = async () => {
    if (!newDirName.trim()) {
      setCreateError("Directory name is required");
      return;
    }

    // Validate directory name (no path separators or special chars)
    if (newDirName.includes("/") || newDirName.includes("\\")) {
      setCreateError("Directory name cannot contain slashes");
      return;
    }

    const basePath = displayDir?.path || "/";
    const newPath = basePath === "/" ? `/${newDirName}` : `${basePath}/${newDirName}`;

    setCreateLoading(true);
    setCreateError(null);

    try {
      const result = await api.createDirectory(newPath);
      if (result.error) {
        setCreateError(result.error);
        return;
      }

      // Clear the cache for the current directory so it reloads with the new dir
      cacheRef.current.delete(basePath);

      // Exit create mode and navigate to the new directory
      setIsCreating(false);
      setNewDirName("");
      setInputPath(newPath + "/");
    } catch (err) {
      setCreateError(err instanceof Error ? err.message : "Failed to create directory");
    } finally {
      setCreateLoading(false);
    }
  };

  const handleCreateKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.nativeEvent.isComposing) return;
    if (e.key === "Enter") {
      e.preventDefault();
      handleCreateDirectory();
    } else if (e.key === "Escape") {
      e.preventDefault();
      handleCancelCreate();
    }
  };

  // Determine if we should show the parent entry
  const showParent = displayDir?.parent && displayDir.parent !== "";

  return (
    <Modal isOpen={isOpen} onClose={onClose} title="Select Directory" className="sm:max-w-lg">
      <div className="flex flex-col gap-3">
        {/* Path input */}
        <Input
          ref={inputRef}
          type="text"
          value={inputPath}
          onChange={(e) => setInputPath(e.target.value)}
          onKeyDown={handleInputKeyDown}
          placeholder="/path/to/directory"
          className="font-mono"
        />

        {/* Current directory indicator */}
        {displayDir && (
          <div
            className={cn(
              "flex min-w-0 flex-col gap-0.5 rounded-md px-2.5 py-1.5 text-sm",
              displayDir.git_head_subject ? "bg-amber-500/10" : "bg-muted"
            )}
          >
            <span className="truncate font-mono text-foreground">
              {displayDir.path}
              {filterPrefix && <span className="text-muted-foreground">/{filterPrefix}*</span>}
            </span>
            {displayDir.git_head_subject && (
              <span
                className="truncate text-xs text-muted-foreground"
                title={displayDir.git_head_subject}
              >
                {displayDir.git_head_subject}
              </span>
            )}
          </div>
        )}

        {/* Quick-jump buttons to git worktree root / main repo root */}
        {(displayDir?.git_repo_root || displayDir?.git_worktree_root) && (
          <div className="flex flex-col gap-1.5">
            {displayDir.git_repo_root && displayDir.git_repo_root !== displayDir.path && (
              <Button
                variant="outline"
                size="sm"
                className="h-auto justify-start gap-2 py-1.5 text-left font-normal"
                onClick={() => setInputPath(displayDir.git_repo_root + "/")}
                title={displayDir.git_repo_root}
              >
                <GitBranchIcon className="shrink-0 text-muted-foreground" />
                <span className="shrink-0">Go to git worktree root</span>
                <span className="min-w-0 flex-1 truncate font-mono text-xs text-muted-foreground">
                  {displayDir.git_repo_root}
                </span>
              </Button>
            )}
            {displayDir.git_worktree_root && displayDir.git_worktree_root !== displayDir.path && (
              <Button
                variant="outline"
                size="sm"
                className="h-auto justify-start gap-2 py-1.5 text-left font-normal"
                onClick={() => setInputPath(displayDir.git_worktree_root + "/")}
                title={displayDir.git_worktree_root}
              >
                <GitBranchIcon className="shrink-0 text-muted-foreground" />
                <span className="shrink-0">Go to git root</span>
                <span className="min-w-0 flex-1 truncate font-mono text-xs text-muted-foreground">
                  {displayDir.git_worktree_root}
                </span>
              </Button>
            )}
          </div>
        )}

        {/* Error message */}
        {error && (
          <div className="rounded-md bg-destructive/10 px-2.5 py-1.5 text-sm text-destructive">
            {error}
          </div>
        )}

        {/* Loading state */}
        {loading && (
          <div className="flex items-center gap-2 px-1 py-4 text-sm text-muted-foreground">
            <Loader2Icon className="size-4 animate-spin" />
            <span>Loading...</span>
          </div>
        )}

        {/* Directory listing */}
        {!loading && !error && (
          <div className="flex max-h-[40vh] flex-col gap-0.5 overflow-y-auto rounded-md border border-border p-1">
            {/* Parent directory entry */}
            {showParent && (
              <button
                type="button"
                className="flex items-center gap-2 rounded-md px-2 py-1.5 text-left text-sm text-muted-foreground transition-colors hover:bg-muted focus-visible:bg-muted focus-visible:outline-none"
                onClick={handleParentClick}
              >
                <CornerLeftUpIcon className="size-4 shrink-0" />
                <span>..</span>
              </button>
            )}

            {/* Directory entries */}
            {filteredEntries.map((entry) => (
              <button
                key={entry.name}
                type="button"
                className="flex items-center gap-2 rounded-md px-2 py-1.5 text-left text-sm transition-colors hover:bg-muted focus-visible:bg-muted focus-visible:outline-none"
                onClick={() => handleEntryClick(entry)}
              >
                <FolderIcon
                  className={cn(
                    "size-4 shrink-0",
                    entry.git_head_subject ? "text-amber-500" : "text-muted-foreground"
                  )}
                />
                <span className="min-w-0 truncate">
                  {filterPrefix &&
                  entry.name.toLowerCase().startsWith(filterPrefix.toLowerCase()) ? (
                    <>
                      <strong className="font-semibold text-foreground">
                        {entry.name.slice(0, filterPrefix.length)}
                      </strong>
                      {entry.name.slice(filterPrefix.length)}
                    </>
                  ) : (
                    entry.name
                  )}
                </span>
                {entry.git_head_subject && (
                  <span
                    className="ml-auto min-w-0 truncate text-xs text-muted-foreground"
                    title={entry.git_head_subject}
                  >
                    {entry.git_head_subject}
                  </span>
                )}
              </button>
            ))}

            {/* Create new directory inline form */}
            {isCreating && (
              <div className="flex items-center gap-2 px-2 py-1.5">
                <FolderPlusIcon className="size-4 shrink-0 text-muted-foreground" />
                <Label htmlFor={createInputId} className="sr-only">
                  New folder name
                </Label>
                <Input
                  id={createInputId}
                  ref={newDirInputRef}
                  type="text"
                  value={newDirName}
                  onChange={(e) => setNewDirName(e.target.value)}
                  onKeyDown={handleCreateKeyDown}
                  placeholder="New folder name"
                  className="h-7 flex-1"
                  disabled={createLoading}
                />
                <Button
                  variant="ghost"
                  size="icon-sm"
                  onClick={handleCreateDirectory}
                  disabled={createLoading || !newDirName.trim()}
                  title="Create"
                >
                  {createLoading ? (
                    <Loader2Icon className="animate-spin" />
                  ) : (
                    <CheckIcon className="text-emerald-600 dark:text-emerald-500" />
                  )}
                </Button>
                <Button
                  variant="ghost"
                  size="icon-sm"
                  onClick={handleCancelCreate}
                  disabled={createLoading}
                  title="Cancel"
                >
                  <XIcon />
                </Button>
              </div>
            )}

            {/* Create error message */}
            {createError && (
              <div className="px-2 py-1 text-xs text-destructive">{createError}</div>
            )}

            {/* Empty state */}
            {filteredEntries.length === 0 && !showParent && !isCreating && (
              <div className="px-2 py-4 text-center text-sm text-muted-foreground">
                {filterPrefix ? "No matching directories" : "No subdirectories"}
              </div>
            )}
          </div>
        )}

        {/* Footer */}
        <div className="flex items-center gap-2 border-t border-border pt-3">
          {/* New Folder button */}
          {!isCreating && !loading && !error && (
            <Button
              variant="outline"
              size="sm"
              onClick={handleStartCreate}
              title="Create new folder"
            >
              <FolderPlusIcon />
              New Folder
            </Button>
          )}
          <div className="flex-1" />
          <Button variant="outline" size="sm" onClick={onClose}>
            Cancel
          </Button>
          <Button size="sm" onClick={handleSelect} disabled={loading || !!error}>
            Select
          </Button>
        </div>
      </div>
    </Modal>
  );
}

export default DirectoryPickerModal;
