// ui/src/vue/components/GitRepoPicker.vue
<!-- Vue port of components/GitRepoPicker.tsx. Lists git repos under $HOME with
     fuzzy filtering. Preserves the grp-* class contract, the dialog
     aria-label "Pick a git repository", the visible title "Pick git
     repository", and the "Close"/"Filter" aria-labels. Uses escapeClose.
     The React <Highlight> subcomponent is reproduced by splitting each path
     into highlighted/plain segments via a computed helper. -->
<template>
  <div v-if="isOpen" class="modal-overlay" @click="onBackdrop">
    <div class="modal grp-modal" role="dialog" aria-label="Pick a git repository">
      <div class="modal-header">
        <h2 class="modal-title">Pick git repository</h2>
        <button class="btn-icon" aria-label="Close" @click="emit('close')">
          <svg fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path
              stroke-linecap="round"
              stroke-linejoin="round"
              :stroke-width="2"
              d="M6 18L18 6M6 6l12 12"
            />
          </svg>
        </button>
      </div>
      <div class="modal-body grp-body">
        <input
          ref="inputRef"
          class="grp-filter"
          type="text"
          v-model="query"
          :placeholder="
            loading ? 'Scanning…' : repos ? `Filter ${repos.length} repos…` : 'Filter repos…'
          "
          spellcheck="false"
          aria-label="Filter"
          @keydown="handleKey"
        />

        <div v-if="error" class="grp-error">{{ error }}</div>

        <div class="grp-list" ref="listRef">
          <button
            v-for="(hit, idx) in filtered"
            :key="hit.repo.path"
            :data-idx="idx"
            type="button"
            :class="`grp-row${idx === activeIdx ? ' grp-row-active' : ''}${hit.repo.path === currentPath ? ' grp-row-current' : ''}`"
            @mouseenter="activeIdx = idx"
            @click="pick(hit.repo.path)"
          >
            <svg
              class="grp-icon"
              fill="none"
              stroke="currentColor"
              viewBox="0 0 24 24"
              aria-hidden="true"
            >
              <path
                stroke-linecap="round"
                stroke-linejoin="round"
                :stroke-width="2"
                d="M3 7v10a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-6l-2-2H5a2 2 0 00-2 2z"
              />
            </svg>
            <span class="grp-main">
              <span class="grp-path" :title="hit.repo.path">
                <template
                  v-for="(seg, si) in highlightSegments(
                    displayPath(hit.repo.path, home),
                    shiftPositions(hit.positions, hit.repo.path, home),
                  )"
                  :key="si"
                >
                  <mark v-if="seg.hit" class="grp-hit">{{ seg.text }}</mark>
                  <template v-else>{{ seg.text }}</template>
                </template>
              </span>
              <span v-if="hit.repo.branch || hit.repo.last_activity" class="grp-meta">
                <span v-if="hit.repo.branch" class="grp-branch" title="Current branch">{{
                  hit.repo.branch
                }}</span>
                <span
                  v-if="hit.repo.last_activity"
                  class="grp-when"
                  :title="new Date(hit.repo.last_activity * 1000).toLocaleString()"
                >
                  {{ formatRelative(hit.repo.last_activity) }}
                </span>
              </span>
            </span>
          </button>
          <div v-if="!loading && repos && filtered.length === 0" class="grp-empty">
            No matching repos.
          </div>
          <div v-if="loading" class="grp-empty">Scanning your home directory…</div>
        </div>

        <div v-if="truncated" class="grp-truncated">Showing first results — try filtering.</div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, nextTick, ref, watch } from "vue";
import { useEscapeClose } from "../composables/escapeClose";

interface GitRepoInfo {
  path: string;
  branch?: string;
  worktree?: boolean;
  last_activity?: number;
}

interface GitReposResponse {
  repos: GitRepoInfo[];
  roots: string[];
  truncated?: boolean;
  elapsed_ms: number;
}

const props = defineProps<{
  isOpen: boolean;
  currentPath?: string;
}>();
const emit = defineEmits<{ (e: "close"): void; (e: "select", path: string): void }>();

const repos = ref<GitRepoInfo[] | null>(null);
const error = ref<string | null>(null);
const loading = ref(false);
const truncated = ref(false);
const home = ref("");
const query = ref("");
const activeIdx = ref(0);
const inputRef = ref<HTMLInputElement | null>(null);
const listRef = ref<HTMLDivElement | null>(null);

useEscapeClose(
  () => props.isOpen,
  () => emit("close"),
);

function formatRelative(ts: number): string {
  const diff = Date.now() / 1000 - ts;
  if (diff < 60) return "just now";
  if (diff < 3600) return `${Math.floor(diff / 60)}m`;
  if (diff < 86400) return `${Math.floor(diff / 3600)}h`;
  if (diff < 86400 * 30) return `${Math.floor(diff / 86400)}d`;
  if (diff < 86400 * 365) return `${Math.floor(diff / (86400 * 30))}mo`;
  return `${Math.floor(diff / (86400 * 365))}y`;
}

function fuzzyScore(text: string, queryStr: string): { score: number; positions: number[] } | null {
  if (!queryStr) return { score: 0, positions: [] };
  const t = text.toLowerCase();
  const q = queryStr.toLowerCase();
  const lastSlash = text.lastIndexOf("/");
  const baseStart = lastSlash + 1;
  const base = t.slice(baseStart);

  const range = (start: number, len: number) => {
    const out: number[] = [];
    for (let i = 0; i < len; i++) out.push(start + i);
    return out;
  };

  if (base.startsWith(q)) {
    return { score: 0 + text.length, positions: range(baseStart, q.length) };
  }
  {
    const i = base.indexOf(q);
    if (i >= 0) {
      return { score: 10000 + i + text.length, positions: range(baseStart + i, q.length) };
    }
  }
  {
    const i = t.indexOf(q);
    if (i >= 0) {
      return { score: 20000 + i + text.length, positions: range(i, q.length) };
    }
  }
  const positions: number[] = [];
  let ti = 0;
  let lastMatch = -1;
  let gaps = 0;
  for (let qi = 0; qi < q.length; qi++) {
    const c = q[qi];
    let found = -1;
    while (ti < t.length) {
      if (t[ti] === c) {
        found = ti;
        ti++;
        break;
      }
      ti++;
    }
    if (found === -1) return null;
    positions.push(found);
    if (lastMatch >= 0) gaps += found - lastMatch - 1;
    lastMatch = found;
  }
  const baseMatches = positions.filter((p) => p >= baseStart).length;
  const tier = baseMatches === q.length ? 30000 : 40000;
  return { score: tier + gaps * 10 + text.length, positions };
}

function displayPath(p: string, h: string): string {
  if (!h) return p;
  if (p === h) return "~";
  if (p.startsWith(h + "/")) return "~" + p.slice(h.length);
  return p;
}

function shiftPositions(positions: number[], realPath: string, h: string): number[] {
  if (!h || !realPath.startsWith(h + "/")) return positions;
  const cut = h.length - 1;
  const out: number[] = [];
  for (const pos of positions) {
    if (pos < h.length) continue;
    out.push(pos - cut);
  }
  return out;
}

function highlightSegments(text: string, positions: number[]): { text: string; hit: boolean }[] {
  if (positions.length === 0) return [{ text, hit: false }];
  const out: { text: string; hit: boolean }[] = [];
  let cursor = 0;
  let i = 0;
  while (i < positions.length) {
    let j = i;
    while (j + 1 < positions.length && positions[j + 1] === positions[j] + 1) j++;
    const start = positions[i];
    const end = positions[j] + 1;
    if (start > cursor) out.push({ text: text.slice(cursor, start), hit: false });
    out.push({ text: text.slice(start, end), hit: true });
    cursor = end;
    i = j + 1;
  }
  if (cursor < text.length) out.push({ text: text.slice(cursor), hit: false });
  return out;
}

const filtered = computed<{ repo: GitRepoInfo; positions: number[] }[]>(() => {
  if (!repos.value) return [];
  if (!query.value) {
    const list = [...repos.value].sort((a, b) => {
      if (props.currentPath) {
        if (a.path === props.currentPath) return -1;
        if (b.path === props.currentPath) return 1;
      }
      const ta = a.last_activity ?? 0;
      const tb = b.last_activity ?? 0;
      if (ta !== tb) return tb - ta;
      return a.path.localeCompare(b.path);
    });
    return list.map((r) => ({ repo: r, positions: [] as number[] }));
  }
  const scored: { repo: GitRepoInfo; score: number; positions: number[] }[] = [];
  for (const r of repos.value) {
    const m = fuzzyScore(r.path, query.value);
    if (m) scored.push({ repo: r, score: m.score, positions: m.positions });
  }
  scored.sort((a, b) => a.score - b.score || a.repo.path.localeCompare(b.repo.path));
  return scored.map(({ repo, positions }) => ({ repo, positions }));
});

function pick(path: string) {
  emit("select", path);
  emit("close");
}

function handleKey(e: KeyboardEvent) {
  if (e.isComposing) return;
  if (e.key === "ArrowDown") {
    e.preventDefault();
    activeIdx.value = Math.min(filtered.value.length - 1, activeIdx.value + 1);
  } else if (e.key === "ArrowUp") {
    e.preventDefault();
    activeIdx.value = Math.max(0, activeIdx.value - 1);
  } else if (e.key === "Enter") {
    e.preventDefault();
    const hit = filtered.value[activeIdx.value];
    if (hit) pick(hit.repo.path);
  }
}

function onBackdrop(e: MouseEvent) {
  if (e.target === e.currentTarget) emit("close");
}

watch(query, () => {
  activeIdx.value = 0;
});

// Scroll the active row into view.
watch(activeIdx, () => {
  if (!listRef.value) return;
  const row = listRef.value.querySelector<HTMLElement>(`[data-idx="${activeIdx.value}"]`);
  if (row) row.scrollIntoView({ block: "nearest" });
});

watch(
  () => props.isOpen,
  (open) => {
    if (!open) return;
    let cancelled = false;
    loading.value = true;
    error.value = null;
    repos.value = null;
    query.value = "";
    activeIdx.value = 0;
    fetch("/api/git/repos")
      .then(async (r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        return (await r.json()) as GitReposResponse;
      })
      .then((d) => {
        if (cancelled) return;
        repos.value = d.repos || [];
        truncated.value = !!d.truncated;
        const r = (d.roots || [])[0];
        if (r) home.value = r;
      })
      .catch((e) => {
        if (!cancelled) error.value = String(e?.message || e);
      })
      .finally(() => {
        if (!cancelled) loading.value = false;
      });

    const isMobile = window.matchMedia("(max-width: 768px)").matches || "ontouchstart" in window;
    if (!isMobile) {
      nextTick(() => inputRef.value?.focus());
    }

    watch(
      () => props.isOpen,
      (stillOpen) => {
        if (!stillOpen) cancelled = true;
      },
      { once: true },
    );
  },
);
</script>

// ui/src/components/GitRepoPicker.tsx
import React, { useEffect, useMemo, useRef, useState } from "react";
import { useEscapeClose } from "./useEscapeClose";

// Picker that lists every git repo under (by default) $HOME and lets the
// user fuzzy-filter the list. Designed for the git-graph viewer where we
// already know the user wants a git working tree.

interface GitRepoInfo {
  path: string;
  branch?: string;
  worktree?: boolean;
  // Unix seconds of the most recent .git activity (HEAD/index/FETCH_HEAD).
  last_activity?: number;
}

function formatRelative(ts: number): string {
  const diff = Date.now() / 1000 - ts;
  if (diff < 60) return "just now";
  if (diff < 3600) return `${Math.floor(diff / 60)}m`;
  if (diff < 86400) return `${Math.floor(diff / 3600)}h`;
  if (diff < 86400 * 30) return `${Math.floor(diff / 86400)}d`;
  if (diff < 86400 * 365) return `${Math.floor(diff / (86400 * 30))}mo`;
  return `${Math.floor(diff / (86400 * 365))}y`;
}

interface GitReposResponse {
  repos: GitRepoInfo[];
  roots: string[];
  truncated?: boolean;
  elapsed_ms: number;
}

interface GitRepoPickerProps {
  isOpen: boolean;
  currentPath?: string;
  onClose: () => void;
  onSelect: (path: string) => void;
}

// Subsequence fuzzy match. Returns a score (lower is better) and the
// match positions inside `text`, or null when there's no match.
//
// Tiers (from best to worst), each ~10× the next:
//   0  basename starts with the query (case-insensitive)
//   1  basename contains the query as a contiguous substring
//   2  query is a contiguous substring anywhere in the path
//   3  basename matches as subsequence
//   4  full path matches as subsequence
// Within a tier, fewer gaps + earlier match wins. Shorter paths break ties.
function fuzzyScore(text: string, query: string): { score: number; positions: number[] } | null {
  if (!query) return { score: 0, positions: [] };
  const t = text.toLowerCase();
  const q = query.toLowerCase();
  const lastSlash = text.lastIndexOf("/");
  const baseStart = lastSlash + 1;
  const base = t.slice(baseStart);

  const range = (start: number, len: number) => {
    const out: number[] = [];
    for (let i = 0; i < len; i++) out.push(start + i);
    return out;
  };

  // Tier 0: basename prefix.
  if (base.startsWith(q)) {
    return { score: 0 + text.length, positions: range(baseStart, q.length) };
  }
  // Tier 1: contiguous substring in basename.
  {
    const i = base.indexOf(q);
    if (i >= 0) {
      return { score: 10000 + i + text.length, positions: range(baseStart + i, q.length) };
    }
  }
  // Tier 2: contiguous substring in full path.
  {
    const i = t.indexOf(q);
    if (i >= 0) {
      return { score: 20000 + i + text.length, positions: range(i, q.length) };
    }
  }
  // Subsequence (tiers 3 & 4): walk through the text once.
  const positions: number[] = [];
  let ti = 0;
  let lastMatch = -1;
  let gaps = 0;
  for (let qi = 0; qi < q.length; qi++) {
    const c = q[qi];
    let found = -1;
    while (ti < t.length) {
      if (t[ti] === c) {
        found = ti;
        ti++;
        break;
      }
      ti++;
    }
    if (found === -1) return null;
    positions.push(found);
    if (lastMatch >= 0) gaps += found - lastMatch - 1;
    lastMatch = found;
  }
  const baseMatches = positions.filter((p) => p >= baseStart).length;
  const tier = baseMatches === q.length ? 30000 : 40000;
  return { score: tier + gaps * 10 + text.length, positions };
}

// Display the path with $HOME collapsed to ~. Filtering still runs on the
// real path so the user can search by absolute path or by anything inside
// their home dir without having to know about the abbreviation.
function displayPath(p: string, home: string): string {
  if (!home) return p;
  if (p === home) return "~";
  if (p.startsWith(home + "/")) return "~" + p.slice(home.length);
  return p;
}

// Shift highlight positions from real-path coordinates into displayPath
// coordinates. Positions inside the elided $HOME prefix are dropped (they
// can't be shown), and the rest are translated by the length difference.
function shiftPositions(positions: number[], realPath: string, home: string): number[] {
  if (!home || !realPath.startsWith(home + "/")) return positions;
  const cut = home.length - 1; // "~" replaces all of home
  const out: number[] = [];
  for (const pos of positions) {
    if (pos < home.length) continue; // hidden inside ~
    out.push(pos - cut);
  }
  return out;
}

function Highlight({ text, positions }: { text: string; positions: number[] }) {
  if (positions.length === 0) return <>{text}</>;
  const out: React.ReactNode[] = [];
  let cursor = 0;
  let i = 0;
  while (i < positions.length) {
    let j = i;
    while (j + 1 < positions.length && positions[j + 1] === positions[j] + 1) j++;
    const start = positions[i];
    const end = positions[j] + 1;
    if (start > cursor) out.push(text.slice(cursor, start));
    out.push(
      <mark key={start} className="grp-hit">
        {text.slice(start, end)}
      </mark>,
    );
    cursor = end;
    i = j + 1;
  }
  if (cursor < text.length) out.push(text.slice(cursor));
  return <>{out}</>;
}

export default function GitRepoPicker({
  isOpen,
  currentPath,
  onClose,
  onSelect,
}: GitRepoPickerProps) {
  const [repos, setRepos] = useState<GitRepoInfo[] | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [truncated, setTruncated] = useState(false);
  const [home, setHome] = useState<string>("");
  const [query, setQuery] = useState("");
  const [activeIdx, setActiveIdx] = useState(0);
  const inputRef = useRef<HTMLInputElement>(null);
  const listRef = useRef<HTMLDivElement>(null);

  useEscapeClose(isOpen, onClose);

  useEffect(() => {
    if (!isOpen) return;
    let cancelled = false;
    setLoading(true);
    setError(null);
    setRepos(null);
    fetch("/api/git/repos")
      .then(async (r) => {
        if (!r.ok) throw new Error(`HTTP ${r.status}`);
        return (await r.json()) as GitReposResponse;
      })
      .then((d) => {
        if (cancelled) return;
        setRepos(d.repos || []);
        setTruncated(!!d.truncated);
        // The server returns the roots it scanned; first one is $HOME by default.
        const r = (d.roots || [])[0];
        if (r) setHome(r);
      })
      .catch((e) => {
        if (!cancelled) setError(String(e?.message || e));
      })
      .finally(() => {
        if (!cancelled) setLoading(false);
      });
    return () => {
      cancelled = true;
    };
  }, [isOpen]);

  useEffect(() => {
    if (!isOpen) return;
    setQuery("");
    setActiveIdx(0);
    // Don't auto-focus the input on mobile; it pops the keyboard.
    const isMobile = window.matchMedia("(max-width: 768px)").matches || "ontouchstart" in window;
    if (!isMobile) {
      // Defer to next tick so the dialog is mounted before focusing.
      const id = window.setTimeout(() => inputRef.current?.focus(), 0);
      return () => window.clearTimeout(id);
    }
  }, [isOpen]);

  const filtered = useMemo(() => {
    if (!repos) return [];
    if (!query) {
      // Default sort: current path first, then most recently active first,
      // alphabetical for any ties or repos with no activity stamp.
      const list = [...repos].sort((a, b) => {
        if (currentPath) {
          if (a.path === currentPath) return -1;
          if (b.path === currentPath) return 1;
        }
        const ta = a.last_activity ?? 0;
        const tb = b.last_activity ?? 0;
        if (ta !== tb) return tb - ta;
        return a.path.localeCompare(b.path);
      });
      return list.map((r) => ({ repo: r, positions: [] as number[] }));
    }
    const scored: { repo: GitRepoInfo; score: number; positions: number[] }[] = [];
    for (const r of repos) {
      const m = fuzzyScore(r.path, query);
      if (m) scored.push({ repo: r, score: m.score, positions: m.positions });
    }
    scored.sort((a, b) => a.score - b.score || a.repo.path.localeCompare(b.repo.path));
    return scored.map(({ repo, positions }) => ({ repo, positions }));
  }, [repos, query, currentPath]);

  useEffect(() => {
    setActiveIdx(0);
  }, [query]);

  // Scroll the active row into view.
  useEffect(() => {
    if (!listRef.current) return;
    const row = listRef.current.querySelector<HTMLElement>(`[data-idx="${activeIdx}"]`);
    if (row) row.scrollIntoView({ block: "nearest" });
  }, [activeIdx]);

  const handleKey = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.nativeEvent.isComposing) return;
    if (e.key === "ArrowDown") {
      e.preventDefault();
      setActiveIdx((i) => Math.min(filtered.length - 1, i + 1));
    } else if (e.key === "ArrowUp") {
      e.preventDefault();
      setActiveIdx((i) => Math.max(0, i - 1));
    } else if (e.key === "Enter") {
      e.preventDefault();
      const hit = filtered[activeIdx];
      if (hit) {
        onSelect(hit.repo.path);
        onClose();
      }
    }
  };

  if (!isOpen) return null;

  return (
    <div
      className="modal-overlay"
      onClick={(e) => {
        if (e.target === e.currentTarget) onClose();
      }}
    >
      <div className="modal grp-modal" role="dialog" aria-label="Pick a git repository">
        <div className="modal-header">
          <h2 className="modal-title">Pick git repository</h2>
          <button onClick={onClose} className="btn-icon" aria-label="Close">
            <svg fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M6 18L18 6M6 6l12 12"
              />
            </svg>
          </button>
        </div>
        <div className="modal-body grp-body">
          <input
            ref={inputRef}
            className="grp-filter"
            type="text"
            value={query}
            onChange={(e) => setQuery(e.target.value)}
            onKeyDown={handleKey}
            placeholder={
              loading ? "Scanning…" : repos ? `Filter ${repos.length} repos…` : "Filter repos…"
            }
            spellCheck={false}
            aria-label="Filter"
          />

          {error && <div className="grp-error">{error}</div>}

          <div className="grp-list" ref={listRef}>
            {filtered.map((hit, idx) => {
              const r = hit.repo;
              const isActive = idx === activeIdx;
              const isCurrent = r.path === currentPath;
              return (
                <button
                  key={r.path}
                  data-idx={idx}
                  type="button"
                  className={`grp-row${isActive ? " grp-row-active" : ""}${
                    isCurrent ? " grp-row-current" : ""
                  }`}
                  onMouseEnter={() => setActiveIdx(idx)}
                  onClick={() => {
                    onSelect(r.path);
                    onClose();
                  }}
                >
                  <svg
                    className="grp-icon"
                    fill="none"
                    stroke="currentColor"
                    viewBox="0 0 24 24"
                    aria-hidden="true"
                  >
                    <path
                      strokeLinecap="round"
                      strokeLinejoin="round"
                      strokeWidth={2}
                      d="M3 7v10a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-6l-2-2H5a2 2 0 00-2 2z"
                    />
                  </svg>
                  <span className="grp-main">
                    <span className="grp-path" title={r.path}>
                      <Highlight
                        text={displayPath(r.path, home)}
                        positions={shiftPositions(hit.positions, r.path, home)}
                      />
                    </span>
                    {(r.branch || r.last_activity) && (
                      <span className="grp-meta">
                        {r.branch && (
                          <span className="grp-branch" title="Current branch">
                            {r.branch}
                          </span>
                        )}
                        {r.last_activity && (
                          <span
                            className="grp-when"
                            title={new Date(r.last_activity * 1000).toLocaleString()}
                          >
                            {formatRelative(r.last_activity)}
                          </span>
                        )}
                      </span>
                    )}
                  </span>
                </button>
              );
            })}
            {!loading && repos && filtered.length === 0 && (
              <div className="grp-empty">No matching repos.</div>
            )}
            {loading && <div className="grp-empty">Scanning your home directory…</div>}
          </div>

          {truncated && <div className="grp-truncated">Showing first results — try filtering.</div>}
        </div>
      </div>
    </div>
  );
}
