// ui/src/vue/components/tools/ScreenshotTool.vue
<!-- Vue port of components/ScreenshotTool.tsx. Default expanded.
     Preserves: .screenshot-tool, .screenshot-tool-header, .screenshot-tool-summary,
     .screenshot-tool-emoji 📷, .screenshot-tool-filename, .screenshot-tool-toggle,
     .screenshot-tool-details, .screenshot-tool-section, .screenshot-tool-label,
     .screenshot-tool-time, .screenshot-tool-image-container, .tool-image-responsive,
     .screenshot-tool-error, .screenshot-tool-success, .screenshot-tool-error-message,
     data-testid tool-call-running/completed. -->
<template>
  <div
    class="screenshot-tool"
    :data-testid="isComplete ? 'tool-call-completed' : 'tool-call-running'"
  >
    <div class="screenshot-tool-header" @click="isExpanded = !isExpanded">
      <div class="screenshot-tool-summary">
        <span class="screenshot-tool-emoji" :class="{ running: isRunning }">📷</span>
        <span class="screenshot-tool-filename" :title="filename">{{ filename }}</span>
        <span v-if="isComplete && hasError" class="screenshot-tool-error">✗</span>
        <span v-if="isComplete && !hasError" class="screenshot-tool-success">✓</span>
      </div>
      <button
        class="screenshot-tool-toggle"
        :aria-label="isExpanded ? 'Collapse' : 'Expand'"
        :aria-expanded="isExpanded"
      >
        <svg
          width="12"
          height="12"
          viewBox="0 0 12 12"
          fill="none"
          xmlns="http://www.w3.org/2000/svg"
          class="tool-chevron"
          :class="{ 'tool-chevron-expanded': isExpanded }"
        >
          <path
            d="M4.5 3L7.5 6L4.5 9"
            stroke="currentColor"
            stroke-width="1.5"
            stroke-linecap="round"
            stroke-linejoin="round"
          />
        </svg>
      </button>
    </div>

    <div v-if="isExpanded" class="screenshot-tool-details">
      <div v-if="isComplete && !hasError && imageUrl" class="screenshot-tool-section">
        <div v-if="executionTime" class="screenshot-tool-label">
          <span>Screenshot:</span>
          <span class="screenshot-tool-time">{{ executionTime }}</span>
        </div>
        <div class="screenshot-tool-image-container">
          <a :href="imageUrl" target="_blank" rel="noopener noreferrer">
            <img
              :src="imageUrl"
              :alt="`Screenshot: ${filename}`"
              class="tool-image-responsive"
              :width="imageWidth || undefined"
              :height="imageHeight || undefined"
            />
          </a>
        </div>
      </div>

      <div v-if="isComplete && hasError" class="screenshot-tool-section">
        <div class="screenshot-tool-label">
          <span>Error:</span>
          <span v-if="executionTime" class="screenshot-tool-time">{{ executionTime }}</span>
        </div>
        <pre class="screenshot-tool-error-message">{{
          toolResult && toolResult[0]?.Text ? toolResult[0].Text : "Screenshot capture failed"
        }}</pre>
      </div>

      <div v-if="isRunning" class="screenshot-tool-section">
        <div class="screenshot-tool-label">Capturing screenshot...</div>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, ref } from "vue";
import type { LLMContent } from "../../../types";

const props = defineProps<{
  toolInput?: unknown;
  isRunning?: boolean;
  toolResult?: LLMContent[];
  hasError?: boolean;
  executionTime?: string;
}>();

// Default to expanded.
const isExpanded = ref(true);

const getStringField = (input: unknown, field: string): string | undefined => {
  if (
    typeof input === "object" &&
    input !== null &&
    field in input &&
    typeof (input as Record<string, unknown>)[field] === "string"
  ) {
    return (input as Record<string, string>)[field];
  }
  return undefined;
};

const filename = computed(
  () =>
    getStringField(props.toolInput, "path") ||
    getStringField(props.toolInput, "id") ||
    getStringField(props.toolInput, "selector") ||
    "screenshot",
);

// Construct image URL from the tool result's image content.
// The server replaces inline base64 data with a URL to /api/message/{id}/image/...
const imageContent = computed(() =>
  props.toolResult && props.toolResult.length >= 2 ? props.toolResult[1] : undefined,
);
const imageUrl = computed(() => imageContent.value?.DisplayImageURL);
const imageWidth = computed(() => imageContent.value?.DisplayWidth);
const imageHeight = computed(() => imageContent.value?.DisplayHeight);

const isComplete = computed(() => !props.isRunning && props.toolResult !== undefined);
</script>

// ui/src/components/ScreenshotTool.tsx
import React, { useState } from "react";
import { LLMContent } from "../types";

interface ScreenshotToolProps {
  // For tool_use (pending state)
  toolInput?: unknown;
  isRunning?: boolean;

  // For tool_result (completed state)
  toolResult?: LLMContent[];
  hasError?: boolean;
  executionTime?: string;
  display?: unknown; // Display data from the tool_result Content
}

function ScreenshotTool({
  toolInput,
  isRunning,
  toolResult,
  hasError,
  executionTime,
  display,
}: ScreenshotToolProps) {
  const [isExpanded, setIsExpanded] = useState(true); // Default to expanded

  // Extract display info from toolInput
  const getPath = (input: unknown): string | undefined => {
    if (
      typeof input === "object" &&
      input !== null &&
      "path" in input &&
      typeof input.path === "string"
    ) {
      return input.path;
    }
    return undefined;
  };

  const getId = (input: unknown): string | undefined => {
    if (
      typeof input === "object" &&
      input !== null &&
      "id" in input &&
      typeof input.id === "string"
    ) {
      return input.id;
    }
    return undefined;
  };

  const getSelector = (input: unknown): string | undefined => {
    if (
      typeof input === "object" &&
      input !== null &&
      "selector" in input &&
      typeof input.selector === "string"
    ) {
      return input.selector;
    }
    return undefined;
  };

  const filename = getPath(toolInput) || getId(toolInput) || getSelector(toolInput) || "screenshot";

  // Use display data passed as prop (from tool_result Content.Display)
  const displayData = display;

  // Construct image URL
  let imageUrl: string | undefined = undefined;
  if (displayData && typeof displayData === "object" && displayData !== null) {
    const url =
      "url" in displayData && typeof displayData.url === "string" ? displayData.url : undefined;
    const path =
      "path" in displayData && typeof displayData.path === "string" ? displayData.path : undefined;
    const id =
      "id" in displayData && typeof displayData.id === "string" ? displayData.id : undefined;

    imageUrl =
      url ||
      (path
        ? `/api/read?path=${encodeURIComponent(path)}`
        : id
          ? `/api/read?path=${encodeURIComponent(id)}`
          : undefined);
  }

  const isComplete = !isRunning && toolResult !== undefined;

  return (
    <div
      className="screenshot-tool"
      data-testid={isComplete ? "tool-call-completed" : "tool-call-running"}
    >
      <div className="screenshot-tool-header" onClick={() => setIsExpanded(!isExpanded)}>
        <div className="screenshot-tool-summary">
          <span className={`screenshot-tool-emoji ${isRunning ? "running" : ""}`}>📷</span>
          <span className="screenshot-tool-filename">{filename}</span>
          {isComplete && hasError && <span className="screenshot-tool-error">✗</span>}
          {isComplete && !hasError && <span className="screenshot-tool-success">✓</span>}
        </div>
        <button
          className="screenshot-tool-toggle"
          aria-label={isExpanded ? "Collapse" : "Expand"}
          aria-expanded={isExpanded}
        >
          <svg
            width="12"
            height="12"
            viewBox="0 0 12 12"
            fill="none"
            xmlns="http://www.w3.org/2000/svg"
            className={`tool-chevron${isExpanded ? " tool-chevron-expanded" : ""}`}
          >
            <path
              d="M4.5 3L7.5 6L4.5 9"
              stroke="currentColor"
              strokeWidth="1.5"
              strokeLinecap="round"
              strokeLinejoin="round"
            />
          </svg>
        </button>
      </div>

      {isExpanded && (
        <div className="screenshot-tool-details">
          {isComplete && !hasError && imageUrl && (
            <div className="screenshot-tool-section">
              {executionTime && (
                <div className="screenshot-tool-label">
                  <span>Screenshot:</span>
                  <span className="screenshot-tool-time">{executionTime}</span>
                </div>
              )}
              <div className="screenshot-tool-image-container">
                <a href={imageUrl} target="_blank" rel="noopener noreferrer">
                  <img
                    src={imageUrl}
                    alt={`Screenshot: ${filename}`}
                    className="tool-image-responsive"
                  />
                </a>
              </div>
            </div>
          )}

          {isComplete && hasError && (
            <div className="screenshot-tool-section">
              <div className="screenshot-tool-label">
                <span>Error:</span>
                {executionTime && <span className="screenshot-tool-time">{executionTime}</span>}
              </div>
              <pre className="screenshot-tool-error-message">
                {toolResult && toolResult[0]?.Text
                  ? toolResult[0].Text
                  : "Screenshot capture failed"}
              </pre>
            </div>
          )}

          {isRunning && (
            <div className="screenshot-tool-section">
              <div className="screenshot-tool-label">Capturing screenshot...</div>
            </div>
          )}
        </div>
      )}
    </div>
  );
}

export default ScreenshotTool;
